<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;

class ProductController extends Controller
{
    /**
     * Data semua produk PT Mitra Abadi Metalindo
     */
    private function allProducts(): array
    {
        return [

            // ─── BESI BETON ───────────────────────────────────────────────
            'besi-beton' => [
                'name'      => 'Besi Beton',
                'title'     => 'Besi Beton (BJTD) – Fungsi, Jenis, Ukuran Standar SNI',
                'subtitle'  => 'Tulangan beton berulir standar SNI 2052:2017 untuk konstruksi bangunan, jembatan, dan infrastruktur.',
                'category'  => 'Baja Tulangan',
                'icon'      => 'Ø',
                'intro'     => 'Besi beton merupakan komponen tulangan utama dalam struktur beton bertulang. Material ini bekerja bersama beton untuk menahan gaya tarik yang tidak mampu ditanggung beton sendiri. Karena itu, pemilihan besi beton yang tepat sangat menentukan kekuatan dan keamanan bangunan. Selain itu, setiap produk harus memenuhi standar SNI agar layak digunakan pada proyek konstruksi.',
                'pengertian'=> 'Besi beton adalah batang baja berulir (deformed bar) yang digunakan sebagai tulangan pada konstruksi beton bertulang. Permukaannya yang berulir meningkatkan daya lekat dengan beton sehingga sambungan menjadi lebih kuat. Dengan demikian, beban struktur dapat disalurkan secara merata ke seluruh elemen bangunan. Selain itu, besi beton diproduksi sesuai standar SNI 2052:2017 yang menjamin konsistensi kualitas.',
                'fungsi'    => [
                    ['judul' => 'Menahan gaya tarik pada beton', 'isi' => 'Beton kuat menahan tekan tetapi lemah menahan tarik. Oleh karena itu, besi beton ditempatkan di zona tarik untuk mengambil alih gaya tersebut sehingga struktur tetap utuh.'],
                    ['judul' => 'Memperkuat pelat lantai dan balok', 'isi' => 'Pada pelat lantai dan balok, besi beton dipasang sesuai perhitungan struktural untuk memastikan kapasitas beban yang cukup dan mencegah retak berlebihan.'],
                    ['judul' => 'Tulangan kolom bangunan bertingkat', 'isi' => 'Kolom memerlukan tulangan longitudinal dan sengkang untuk menahan beban aksial dan lateral. Besi beton menjadi komponen utama dalam sistem ini.'],
                    ['judul' => 'Penguatan fondasi dan pondasi tiang', 'isi' => 'Pondasi telapak, raft, dan tiang pancang menggunakan besi beton untuk mendistribusikan beban bangunan ke tanah secara aman dan merata.'],
                ],
                'jenis'     => [
                    ['nama' => 'Besi Beton Ulir (BJTD 40)', 'deskripsi' => 'Baja tulangan deform dengan tegangan leleh minimum 400 MPa. Cocok untuk bangunan bertingkat rendah hingga menengah dan infrastruktur umum.'],
                    ['nama' => 'Besi Beton Ulir (BJTD 50)', 'deskripsi' => 'Kekuatan lebih tinggi dengan tegangan leleh minimum 500 MPa. Digunakan pada proyek berat seperti jembatan, bendungan, dan gedung tinggi.'],
                    ['nama' => 'Besi Beton Polos (BJTP 24)', 'deskripsi' => 'Batang baja dengan permukaan halus tanpa ulir. Umumnya digunakan untuk sengkang, beugel, dan tulangan distribusi pada komponen sekunder.'],
                ],
                'keunggulan' => [
                    'Kekuatan tarik tinggi sesuai standar SNI 2052:2017',
                    'Daya lekat optimal dengan beton berkat profil ulir',
                    'Tersedia diameter lengkap dari Ø8 hingga Ø32 mm',
                    'Konsistensi dimensi dan berat per meter terjamin',
                    'Cocok untuk semua jenis konstruksi beton bertulang',
                    'Ready stock dengan pengiriman cepat ke seluruh wilayah',
                ],
                'ukuran_intro' => 'Besi beton tersedia dalam berbagai diameter sesuai kebutuhan struktur. Panjang standar adalah 12 meter, namun pemotongan sesuai kebutuhan dapat dilayani.',
                'tabel_header' => ['Diameter', 'Berat (kg/m)', 'Grade', 'Standar', 'Panjang'],
                'tabel_data'   => [
                    ['Ø8 mm',  '0,395', 'BJTD 40', 'SNI 2052:2017', '12 m'],
                    ['Ø10 mm', '0,617', 'BJTD 40', 'SNI 2052:2017', '12 m'],
                    ['Ø12 mm', '0,888', 'BJTD 40', 'SNI 2052:2017', '12 m'],
                    ['Ø16 mm', '1,580', 'BJTD 40', 'SNI 2052:2017', '12 m'],
                    ['Ø19 mm', '2,230', 'BJTD 40', 'SNI 2052:2017', '12 m'],
                    ['Ø22 mm', '2,980', 'BJTD 50', 'SNI 2052:2017', '12 m'],
                    ['Ø25 mm', '3,850', 'BJTD 50', 'SNI 2052:2017', '12 m'],
                    ['Ø32 mm', '6,310', 'BJTD 50', 'SNI 2052:2017', '12 m'],
                ],
                'kesimpulan' => 'Besi beton merupakan tulangan yang tidak tergantikan dalam konstruksi beton bertulang. Dengan memilih grade dan diameter yang tepat sesuai perhitungan struktur, kekuatan dan keamanan bangunan dapat terjamin. Selain itu, penggunaan besi beton berstandar SNI memastikan material memenuhi persyaratan teknis proyek.',
                'spesifikasi' => ['Standar' => 'SNI 2052:2017', 'Grade' => 'BJTD 40 / BJTD 50', 'Diameter' => 'Ø8 – Ø32 mm', 'Panjang' => '12 meter', 'Permukaan' => 'Ulir (Deformed)'],
            ],

            // ─── BESI SIKU ───────────────────────────────────────────────
            'besi-siku' => [
                'name'      => 'Besi Siku',
                'title'     => 'Besi Siku – Jenis, Ukuran, dan Fungsi untuk Konstruksi',
                'subtitle'  => 'Profil baja berbentuk L untuk rangka atap, bracing, dan berbagai konstruksi ringan maupun berat.',
                'category'  => 'Baja Profil',
                'icon'      => 'L',
                'intro'     => 'Besi siku adalah profil baja berbentuk sudut 90° yang banyak digunakan dalam konstruksi rangka, bracing, dan penopang. Material ini menawarkan keseimbangan antara kekuatan dan kemudahan fabrikasi. Karena itu, besi siku menjadi salah satu profil paling serbaguna di industri konstruksi. Selain itu, ketersediaannya dalam berbagai ukuran memudahkan penyesuaian dengan berbagai kebutuhan lapangan.',
                'pengertian'=> 'Besi siku adalah batang baja berbentuk huruf L dengan dua sayap yang membentuk sudut 90°. Profil ini dapat berupa sama sisi (equal angle) maupun tidak sama sisi (unequal angle). Dengan demikian, besi siku dapat digunakan pada berbagai konfigurasi struktur. Selain itu, kemampuannya menahan tekuk menjadikannya pilihan utama untuk rangka dan bracing.',
                'fungsi'    => [
                    ['judul' => 'Rangka atap dan kuda-kuda', 'isi' => 'Besi siku digunakan sebagai batang diagonal dan vertikal pada rangka kuda-kuda baja, menjaga kestabilan bentuk dan mendistribusikan beban atap secara merata.'],
                    ['judul' => 'Bracing dan pengaku lateral', 'isi' => 'Dipasang diagonal pada dinding dan kolom untuk menahan gaya lateral akibat angin dan gempa, meningkatkan kekakuan keseluruhan struktur bangunan.'],
                    ['judul' => 'Rangka rak dan platform industri', 'isi' => 'Digunakan sebagai rangka rak penyimpanan, platform kerja, dan tangga baja karena kemudahan sambungan baut maupun las.'],
                    ['judul' => 'Penopang dan bracket', 'isi' => 'Besi siku banyak dipakai sebagai bracket penopang peralatan mekanikal, panel, dan komponen bangunan lainnya karena bentuknya yang kokoh dan mudah dipasang.'],
                ],
                'jenis'     => [
                    ['nama' => 'Besi Siku Sama Sisi (Equal Angle)', 'deskripsi' => 'Kedua sayap memiliki lebar yang sama. Cocok untuk bracing simetris, rangka, dan aplikasi umum yang membutuhkan kekuatan seimbang pada dua arah.'],
                    ['nama' => 'Besi Siku Tidak Sama Sisi (Unequal Angle)', 'deskripsi' => 'Kedua sayap memiliki lebar berbeda, memberikan kekuatan lebih pada satu arah. Digunakan saat beban dominan bekerja pada satu sumbu tertentu.'],
                    ['nama' => 'Besi Siku Stainless Steel', 'deskripsi' => 'Profil siku dari baja tahan karat untuk lingkungan korosif seperti industri makanan, kimia, dan area outdoor yang memerlukan ketahanan terhadap karat.'],
                ],
                'keunggulan' => [
                    'Kekuatan tekuk tinggi pada kedua arah sayap',
                    'Mudah disambung dengan baut maupun las',
                    'Tersedia dalam ukuran 25×25 mm hingga 200×200 mm',
                    'Material SS400 berkualitas tinggi sesuai standar JIS',
                    'Berat per meter konsisten untuk kemudahan perhitungan struktur',
                    'Tersedia dalam panjang 6m dan 12m, bisa dipotong sesuai kebutuhan',
                ],
                'ukuran_intro' => 'Besi siku tersedia dalam berbagai ukuran dengan panjang standar 6 meter dan 12 meter. Berikut tabel ukuran yang tersedia:',
                'tabel_header' => ['Ukuran (mm)', 'Tebal (mm)', 'Berat (kg/m)', 'Grade', 'Panjang'],
                'tabel_data'   => [
                    ['25 × 25', '3', '1,12', 'SS400', '6m / 12m'],
                    ['40 × 40', '4', '2,42', 'SS400', '6m / 12m'],
                    ['50 × 50', '5', '3,77', 'SS400', '6m / 12m'],
                    ['60 × 60', '6', '5,42', 'SS400', '6m / 12m'],
                    ['75 × 75', '7', '7,95', 'SS400', '6m / 12m'],
                    ['100 × 100', '10', '14,80', 'SS400', '6m / 12m'],
                    ['125 × 125', '12', '22,70', 'SS400', '6m / 12m'],
                    ['150 × 150', '15', '33,80', 'SS400', '6m / 12m'],
                ],
                'kesimpulan' => 'Besi siku merupakan profil baja yang sangat serbaguna dan efisien untuk berbagai aplikasi konstruksi. Dengan memilih ukuran dan tebal yang sesuai perhitungan struktural, kekuatan rangka dan bracing dapat dioptimalkan. Selain itu, kemudahan fabrikasi menjadikan besi siku pilihan utama kontraktor dan fabrikator baja.',
                'spesifikasi' => ['Standar' => 'JIS G3101 / SNI', 'Grade' => 'SS400', 'Ukuran' => '25×25 – 200×200 mm', 'Panjang' => '6m / 12m', 'Tipe' => 'Equal & Unequal'],
            ],

            // ─── BESI VIRKAN / WF ────────────────────────────────────────
            'besi-virkan' => [
                'name'      => 'Besi Virkan (WF)',
                'title'     => 'Besi Virkan / Baja WF – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Baja Wide Flange (WF) untuk balok dan kolom struktur bangunan bertingkat, jembatan, dan konstruksi berat.',
                'category'  => 'Baja Profil',
                'icon'      => 'H',
                'intro'     => 'Besi virkan atau baja WF (Wide Flange) adalah profil baja struktural paling umum digunakan pada bangunan bertingkat dan konstruksi berat. Material ini memiliki penampang berbentuk huruf H dengan sayap lebar yang memberikan momen inersia tinggi. Karena itu, baja WF mampu menahan beban lentur dan aksial yang besar secara efisien. Selain itu, profil ini tersedia dalam berbagai ukuran untuk menyesuaikan kebutuhan struktural.',
                'pengertian'=> 'Besi virkan adalah istilah lokal untuk baja profil Wide Flange (WF), yaitu baja dengan penampang berbentuk I atau H dengan sayap lebar dan sejajar. Dimensi sayap yang lebar menghasilkan momen inersia yang tinggi pada kedua sumbu. Dengan demikian, profil ini sangat efisien untuk menahan beban lentur pada balok maupun beban aksial pada kolom. Selain itu, baja WF diproduksi mengikuti standar JIS G3101 atau ASTM A36.',
                'fungsi'    => [
                    ['judul' => 'Balok utama bangunan bertingkat', 'isi' => 'Baja WF digunakan sebagai balok lantai dan balok girder pada gedung bertingkat untuk menopang beban pelat lantai dan diteruskan ke kolom.'],
                    ['judul' => 'Kolom struktur bangunan', 'isi' => 'Profil WF juga banyak digunakan sebagai kolom karena sayap lebarnya memberikan kekakuan dua arah yang baik, ideal untuk menahan beban gravitasi dan lateral.'],
                    ['judul' => 'Rangka jembatan dan jalan layang', 'isi' => 'Pada konstruksi jembatan, baja WF digunakan sebagai girder utama yang menopang dek jembatan dan menyalurkan beban ke perletakan.'],
                    ['judul' => 'Konstruksi baja industri dan gudang', 'isi' => 'Bangunan industri, gudang, dan hanggar menggunakan portal rangka baja dengan profil WF untuk mencapai bentang lebar tanpa kolom pengganggu di tengah.'],
                ],
                'jenis'     => [
                    ['nama' => 'WF Standar (Wide Flange)', 'deskripsi' => 'Profil dengan rasio tinggi badan terhadap lebar sayap mendekati 1:1. Optimal untuk kolom karena kekakuan seimbang pada dua sumbu.'],
                    ['nama' => 'WF Tinggi (Slim Section)', 'deskripsi' => 'Profil dengan badan lebih tinggi relatif terhadap sayap. Lebih efisien sebagai balok karena momen inersia sumbu kuat yang lebih besar.'],
                    ['nama' => 'WF Berat (Heavy Section)', 'deskripsi' => 'Ukuran besar dengan tebal sayap dan badan yang lebih besar untuk beban sangat berat, digunakan pada gedung super tinggi dan jembatan besar.'],
                ],
                'keunggulan' => [
                    'Momen inersia tinggi, efisien menahan beban lentur',
                    'Tersedia ukuran WF 100×100 hingga WF 400×400 mm',
                    'Material SS400 berkualitas sesuai JIS G3101',
                    'Mudah disambung dengan baut mutu tinggi atau las',
                    'Rasio kekuatan terhadap berat yang sangat baik',
                    'Kompatibel dengan sistem konstruksi baja komposit',
                ],
                'ukuran_intro' => 'Baja WF tersedia dalam berbagai ukuran H×B (tinggi × lebar sayap). Berat per meter bervariasi sesuai ukuran dan tebal profil.',
                'tabel_header' => ['Ukuran H×B (mm)', 'Tebal Badan (mm)', 'Tebal Sayap (mm)', 'Berat (kg/m)', 'Panjang'],
                'tabel_data'   => [
                    ['100 × 100', '6', '8',  '17,2', '6m / 12m'],
                    ['150 × 150', '7', '10', '31,5', '6m / 12m'],
                    ['200 × 200', '8', '12', '50,5', '6m / 12m'],
                    ['250 × 250', '9', '14', '72,4', '6m / 12m'],
                    ['300 × 300', '10','15', '94,0', '6m / 12m'],
                    ['350 × 350', '12','19', '137',  '6m / 12m'],
                    ['400 × 400', '13','21', '172',  '6m / 12m'],
                ],
                'kesimpulan' => 'Besi virkan / baja WF adalah profil struktural yang paling efisien untuk balok dan kolom bangunan modern. Dengan memilih ukuran yang sesuai perhitungan struktur, efisiensi material dapat dimaksimalkan tanpa mengorbankan keamanan. Selain itu, kemudahan fabrikasi dan pemasangan menjadikan baja WF pilihan utama kontraktor konstruksi baja.',
                'spesifikasi' => ['Standar' => 'JIS G3101 / ASTM A36', 'Grade' => 'SS400 / A36', 'Ukuran' => 'WF 100 – WF 400', 'Panjang' => '6m / 9m / 12m', 'Tipe' => 'Wide Flange'],
            ],

            // ─── H-BEAM ──────────────────────────────────────────────────
            'h-beam' => [
                'name'      => 'H-Beam',
                'title'     => 'H-Beam – Pengertian, Fungsi, Jenis, Ukuran untuk Konstruksi',
                'subtitle'  => 'Baja profil H-Beam untuk kolom struktur bangunan, jembatan, dan konstruksi pelabuhan.',
                'category'  => 'Baja Profil',
                'icon'      => 'I',
                'intro'     => 'H-Beam adalah profil baja struktural berbentuk huruf H yang banyak digunakan sebagai kolom pada konstruksi bangunan berat dan jembatan. Material ini memiliki karakteristik sayap dan badan dengan tebal hampir merata, menghasilkan kekuatan seimbang pada dua sumbu. Karena itu, H-Beam sangat ideal sebagai elemen kolom pada gedung bertingkat tinggi. Selain itu, dimensinya yang presisi memudahkan proses fabrikasi dan pemasangan.',
                'pengertian'=> 'H-Beam adalah profil baja dengan penampang berbentuk huruf H di mana lebar sayap sama atau hampir sama dengan tinggi badan profil. Perbedaan utama dengan WF adalah H-Beam memiliki proporsi yang lebih "gemuk" sehingga momen inersia pada sumbu lemah lebih besar. Dengan demikian, H-Beam lebih efisien sebagai kolom. Selain itu, permukaannya yang rata memudahkan sambungan baseplate dan pelat pengaku.',
                'fungsi'    => [
                    ['judul' => 'Kolom utama bangunan bertingkat tinggi', 'isi' => 'H-Beam digunakan sebagai kolom pada gedung 10 lantai ke atas karena kekuatan dua arahnya yang seimbang mampu menahan beban gravitasi dan gaya lateral gempa secara bersamaan.'],
                    ['judul' => 'Tiang pancang baja (H-Pile)', 'isi' => 'Dalam aplikasi fondasi, H-Beam digunakan sebagai tiang pancang yang ditempatkan ke lapisan tanah keras untuk menyalurkan beban bangunan ke tanah.'],
                    ['judul' => 'Girder jembatan dan jalan layang', 'isi' => 'H-Beam ukuran besar digunakan sebagai girder jembatan dan overpass karena kemampuannya menopang beban dinamis yang besar dari kendaraan.'],
                    ['judul' => 'Konstruksi pelabuhan dan dermaga', 'isi' => 'Pada dermaga dan pelabuhan, H-Beam digunakan sebagai tiang dan penopang struktur yang harus tahan terhadap beban dinamis gelombang dan kapal.'],
                ],
                'jenis'     => [
                    ['nama' => 'H-Beam Standar (HW)', 'deskripsi' => 'Wide H-Beam dengan lebar sayap sama dengan tinggi profil. Optimal untuk kolom karena kekakuan seimbang pada sumbu X dan Y.'],
                    ['nama' => 'H-Beam Medium (HM)', 'deskripsi' => 'Proporsi sedang antara tinggi badan dan lebar sayap. Fleksibel digunakan untuk balok maupun kolom sesuai kondisi struktur.'],
                    ['nama' => 'H-Beam Narrow (HN)', 'deskripsi' => 'Lebar sayap lebih sempit relatif terhadap tinggi badan. Efisien sebagai balok dengan momen inersia sumbu kuat yang lebih besar.'],
                ],
                'keunggulan' => [
                    'Kekuatan dua arah yang seimbang, ideal untuk kolom',
                    'Tersedia ukuran H 100 mm hingga H 400 mm',
                    'Material SS400 memenuhi standar JIS G3101',
                    'Permukaan rata memudahkan sambungan baseplate',
                    'Dapat digunakan sebagai tiang pancang (H-Pile)',
                    'Fabrikasi dan pemasangan yang mudah dan efisien',
                ],
                'ukuran_intro' => 'H-Beam tersedia dalam berbagai ukuran dengan panjang standar 6 meter dan 12 meter. Ukuran dinyatakan dalam tinggi (H) × lebar (B) profil.',
                'tabel_header' => ['Ukuran H×B (mm)', 'Tebal Badan (mm)', 'Tebal Sayap (mm)', 'Berat (kg/m)', 'Panjang'],
                'tabel_data'   => [
                    ['100 × 100', '6',  '8',  '17,2', '6m / 12m'],
                    ['150 × 150', '7',  '10', '31,5', '6m / 12m'],
                    ['200 × 200', '8',  '12', '50,5', '6m / 12m'],
                    ['250 × 250', '9',  '14', '72,4', '6m / 12m'],
                    ['300 × 300', '10', '15', '94,0', '6m / 12m'],
                    ['350 × 350', '12', '19', '137',  '6m / 12m'],
                    ['400 × 400', '13', '21', '172',  '6m / 12m'],
                ],
                'kesimpulan' => 'H-Beam adalah profil baja yang sangat andal untuk kolom bangunan tinggi dan konstruksi berat. Dengan proporsi sayap yang lebar dan simetris, H-Beam memberikan kekuatan optimal pada kedua sumbu. Selain itu, fleksibilitasnya sebagai kolom, girder, maupun tiang pancang menjadikannya salah satu profil baja paling penting dalam proyek konstruksi modern.',
                'spesifikasi' => ['Standar' => 'JIS G3101 / ASTM', 'Grade' => 'SS400', 'Ukuran' => 'H 100 – H 400 mm', 'Panjang' => '6m / 12m', 'Tipe' => 'HW / HM / HN'],
            ],

            // ─── UNP ─────────────────────────────────────────────────────
            'unp' => [
                'name'      => 'Kanal UNP',
                'title'     => 'Kanal UNP – Pengertian, Fungsi, Ukuran Standar Konstruksi',
                'subtitle'  => 'Profil kanal U untuk rangka bangunan, purlin, gording atap, dan berbagai aplikasi struktural.',
                'category'  => 'Baja Profil',
                'icon'      => 'U',
                'intro'     => 'Kanal UNP adalah profil baja berbentuk huruf U yang banyak digunakan sebagai gording atap, rangka sekunder, dan penopang pada berbagai konstruksi. Material ini menawarkan kekuatan lentur yang baik dengan berat yang relatif ringan. Karena itu, kanal UNP menjadi pilihan populer untuk struktural sekunder bangunan industri dan komersial. Selain itu, kemudahan fabrikasi menjadikannya efisien dalam proyek dengan waktu pelaksanaan terbatas.',
                'pengertian'=> 'Kanal UNP (U-Profile Normal) adalah profil baja canai panas dengan penampang berbentuk huruf U. Profil ini terdiri dari badan vertikal dan dua sayap horizontal yang sejajar. Dengan demikian, kanal UNP memiliki momen inersia yang baik pada sumbu horizontal. Selain itu, profil U memudahkan pemasangan komponen lain di dalamnya, menjadikannya serbaguna untuk berbagai aplikasi konstruksi.',
                'fungsi'    => [
                    ['judul' => 'Gording dan purlin atap', 'isi' => 'Kanal UNP dipasang horizontal di atas kuda-kuda atau portal sebagai gording yang menopang penutup atap. Bentuk U-nya memungkinkan sambungan yang kaku dengan rangka utama.'],
                    ['judul' => 'Rangka sekunder bangunan industri', 'isi' => 'Digunakan sebagai balok anak dan rangka dinding sekunder pada bangunan industri, gudang, dan hangar untuk mendistribusikan beban ke rangka utama.'],
                    ['judul' => 'Rel dan lintasan material handling', 'isi' => 'Profil U banyak digunakan sebagai rel untuk sistem material handling ringan, konveyor, dan lintasan trolley di fasilitas industri.'],
                    ['judul' => 'Penopang pipa dan kabel (cable tray)', 'isi' => 'Kanal UNP digunakan sebagai penopang pipa mekanikal dan kabel elektrikal pada bangunan industri dan komersial, dipasang di dinding atau langit-langit.'],
                ],
                'jenis'     => [
                    ['nama' => 'UNP Standar (Hot Rolled)', 'deskripsi' => 'Diproduksi melalui proses canai panas (hot rolling) dengan dimensi presisi sesuai standar DIN 1025. Kekuatan tinggi dan cocok untuk gording dan rangka sekunder.'],
                    ['nama' => 'UNP Galvanis', 'deskripsi' => 'Kanal UNP dengan lapisan galvanis untuk ketahanan korosi tinggi, ideal untuk bangunan di lingkungan lembab, pesisir, atau area industri kimia.'],
                    ['nama' => 'UNP Stainless Steel', 'deskripsi' => 'Untuk aplikasi yang membutuhkan ketahanan korosi sangat tinggi seperti industri makanan, farmasi, dan area outdoor dengan paparan elemen agresif.'],
                ],
                'keunggulan' => [
                    'Momen inersia yang baik untuk menahan beban lentur',
                    'Tersedia ukuran UNP 80 hingga UNP 300',
                    'Material ST37/SS400 berkualitas standar JIS/DIN',
                    'Mudah disambung dengan baut dan las',
                    'Berat per meter konsisten untuk perhitungan beban',
                    'Tersedia panjang 6m dan 12m, bisa dipotong',
                ],
                'ukuran_intro' => 'Kanal UNP tersedia dalam berbagai ukuran tinggi badan. Berat per meter bervariasi sesuai dimensi profil.',
                'tabel_header' => ['Tipe', 'H (mm)', 'B (mm)', 'Tebal Badan (mm)', 'Berat (kg/m)'],
                'tabel_data'   => [
                    ['UNP 80',  '80',  '45', '6', '8,64'],
                    ['UNP 100', '100', '50', '6', '10,6'],
                    ['UNP 120', '120', '55', '7', '13,4'],
                    ['UNP 140', '140', '60', '7', '16,0'],
                    ['UNP 160', '160', '65', '7,5', '18,8'],
                    ['UNP 180', '180', '70', '8', '22,0'],
                    ['UNP 200', '200', '75', '8,5', '25,3'],
                    ['UNP 300', '300', '100', '9', '46,2'],
                ],
                'kesimpulan' => 'Kanal UNP adalah profil struktural sekunder yang efisien dan serbaguna. Dengan memilih ukuran yang sesuai perhitungan beban, gording, rangka, dan penopang dapat bekerja optimal. Selain itu, ketersediaan berbagai ukuran dan kemudahan fabrikasi menjadikan kanal UNP komponen penting dalam konstruksi baja modern.',
                'spesifikasi' => ['Standar' => 'DIN 1025 / JIS', 'Grade' => 'ST37 / SS400', 'Ukuran' => 'UNP 80 – UNP 300', 'Panjang' => '6m / 12m', 'Tipe' => 'Hot Rolled'],
            ],

            // ─── CNP ─────────────────────────────────────────────────────
            'cnp' => [
                'name'      => 'Kanal CNP',
                'title'     => 'Kanal CNP (Lips Channel) – Fungsi, Jenis, Ukuran Konstruksi',
                'subtitle'  => 'Kanal C dengan bibir (lips channel) untuk gording atap, rangka dinding, dan struktur baja ringan.',
                'category'  => 'Baja Profil',
                'icon'      => 'C',
                'intro'     => 'Kanal CNP atau Lips Channel adalah profil baja berbentuk huruf C dengan penambahan bibir (lips) di ujung sayap yang meningkatkan kekakuan profil. Material ini banyak digunakan sebagai gording atap, rangka dinding, dan purlin pada bangunan industri dan komersial. Karena itu, kanal CNP menjadi pilihan utama untuk struktural sekunder yang membutuhkan efisiensi berat dan kekakuan. Selain itu, beratnya lebih ringan dibanding profil hot-rolled dengan fungsi serupa.',
                'pengertian'=> 'Kanal CNP (Cold-formed Normal Profile) atau Lips Channel adalah profil baja cold-formed berbentuk huruf C dengan bibir horizontal di ujung kedua sayap. Bibir ini berfungsi meningkatkan kekakuan lokal profil sehingga dapat menahan beban lebih efisien. Dengan demikian, CNP memiliki rasio kekuatan terhadap berat yang sangat baik. Selain itu, profil ini diproduksi melalui proses cold-forming (pembentukan dingin) sehingga dimensinya sangat presisi.',
                'fungsi'    => [
                    ['judul' => 'Gording dan purlin atap baja', 'isi' => 'CNP dipasang horizontal di atas kuda-kuda atau portal baja sebagai gording yang menopang atap. Profil C dengan bibir memberikan kekakuan lateral yang baik.'],
                    ['judul' => 'Rangka dinding eksterior dan interior', 'isi' => 'Digunakan sebagai girt (rangka dinding horizontal) pada bangunan industri untuk menopang dinding panel dan mengalirkan beban angin ke kolom utama.'],
                    ['judul' => 'Reng dan batten pada atap metal', 'isi' => 'CNP ukuran kecil digunakan sebagai reng yang menopang penutup atap metal, dipasang tegak lurus terhadap gording dengan jarak tertentu.'],
                    ['judul' => 'Rangka plafon dan partisi', 'isi' => 'Pada bangunan komersial dan industri, CNP digunakan sebagai rangka plafon suspensi dan partisi dinding untuk kebutuhan interior yang ringan.'],
                ],
                'jenis'     => [
                    ['nama' => 'CNP Baja Hitam', 'deskripsi' => 'Material baja karbon tanpa lapisan pelindung. Cocok untuk penggunaan di dalam ruangan atau dengan perlindungan cat. Harga lebih ekonomis.'],
                    ['nama' => 'CNP Galvanis', 'deskripsi' => 'Dilapisi zinc melalui proses galvanisasi untuk ketahanan korosi. Ideal untuk bangunan di lingkungan lembab atau area dengan resiko karat tinggi.'],
                    ['nama' => 'CNP Galvalum', 'deskripsi' => 'Dilapisi campuran zinc-aluminium yang memberikan ketahanan korosi lebih baik dari galvanis biasa. Pilihan ekonomis untuk ketahanan jangka panjang.'],
                ],
                'keunggulan' => [
                    'Rasio kekuatan terhadap berat yang sangat efisien',
                    'Bibir (lips) meningkatkan kekakuan lokal profil',
                    'Tersedia ukuran 60×30 mm hingga 200×75 mm',
                    'Dimensi presisi hasil cold-forming',
                    'Mudah dipotong, dibor, dan disambung di lapangan',
                    'Tersedia dalam varian hitam, galvanis, dan galvalum',
                ],
                'ukuran_intro' => 'Kanal CNP tersedia dalam berbagai ukuran H×B (tinggi × lebar). Tebal material bervariasi sesuai kebutuhan beban.',
                'tabel_header' => ['Ukuran H×B (mm)', 'Tebal (mm)', 'Berat (kg/m)', 'Material', 'Panjang'],
                'tabel_data'   => [
                    ['60 × 30',  '2,3', '2,05', 'Hitam / Galvanis', '6m'],
                    ['75 × 45',  '2,3', '2,65', 'Hitam / Galvanis', '6m'],
                    ['100 × 50', '2,3', '3,35', 'Hitam / Galvanis', '6m'],
                    ['100 × 50', '3,2', '4,65', 'Hitam / Galvanis', '6m'],
                    ['125 × 50', '2,3', '3,90', 'Hitam / Galvanis', '6m'],
                    ['150 × 65', '3,2', '6,58', 'Hitam / Galvanis', '6m'],
                    ['200 × 75', '3,2', '8,77', 'Hitam / Galvanis', '6m'],
                ],
                'kesimpulan' => 'Kanal CNP adalah profil struktural sekunder yang efisien dan ringan untuk gording, rangka dinding, dan aplikasi baja ringan. Dengan memilih tebal dan ukuran yang sesuai perhitungan beban, efisiensi material dapat dimaksimalkan. Selain itu, ketersediaan dalam varian hitam, galvanis, dan galvalum memungkinkan pemilihan material sesuai kondisi lingkungan proyek.',
                'spesifikasi' => ['Standar' => 'SNI / JIS', 'Grade' => 'G250 / G300', 'Ukuran' => '60×30 – 200×75 mm', 'Panjang' => '6m standar', 'Tipe' => 'Cold-Formed'],
            ],

            // ─── PLAT HITAM ──────────────────────────────────────────────
            'plat-hitam' => [
                'name'      => 'Plat Hitam',
                'title'     => 'Plat Hitam – Pengertian, Fungsi, Ukuran Standar Hot Rolled',
                'subtitle'  => 'Plat baja hitam hasil hot rolling untuk fabrikasi berat, konstruksi kapal, tangki, dan industri berat.',
                'category'  => 'Plat & Sheet',
                'icon'      => '▬',
                'intro'     => 'Plat hitam atau plat baja hitam adalah produk baja berbentuk lembaran datar hasil proses pengerolan panas (hot rolling) yang banyak digunakan dalam fabrikasi berat dan konstruksi industri. Material ini menjadi bahan baku utama untuk pembuatan tangki, kapal, jembatan, dan berbagai komponen struktural. Karena itu, plat hitam tersedia dalam berbagai ketebalan untuk memenuhi berbagai kebutuhan teknis. Selain itu, sifat mekaniknya yang baik menjadikannya material pilihan utama industri berat.',
                'pengertian'=> 'Plat hitam adalah lembaran baja karbon rendah hingga sedang yang diproduksi melalui proses hot rolling pada suhu tinggi. Permukaan plat berwarna gelap (hitam) karena lapisan oksida yang terbentuk selama proses pendinginan. Dengan demikian, plat ini memiliki toleransi dimensi yang lebih longgar dibanding cold-rolled. Selain itu, proses hot rolling menghasilkan sifat material yang homogen dan isotropik, ideal untuk fabrikasi struktural.',
                'fungsi'    => [
                    ['judul' => 'Fabrikasi tangki dan bejana tekan', 'isi' => 'Plat hitam merupakan bahan baku utama pembuatan tangki penyimpanan, bejana tekan (pressure vessel), dan reaktor industri kimia dan migas.'],
                    ['judul' => 'Konstruksi kapal dan lambung kapal', 'isi' => 'Industri perkapalan menggunakan plat hitam tebal sebagai bahan lambung kapal, sekat, dan deck karena kekuatan dan kemampuan las yang baik.'],
                    ['judul' => 'Baseplate kolom dan pelat sambungan', 'isi' => 'Pada konstruksi baja, plat hitam digunakan sebagai baseplate pada dasar kolom dan pelat penyambung antar elemen struktural.'],
                    ['judul' => 'Pembuatan mesin dan peralatan industri', 'isi' => 'Berbagai komponen mesin, frame, dan chassis peralatan industri dibuat dari plat hitam karena kemudahan pemesinan dan pengelasan.'],
                ],
                'jenis'     => [
                    ['nama' => 'Plat Hitam Tipis (3–12 mm)', 'deskripsi' => 'Untuk aplikasi fabrikasi ringan hingga menengah, pembuatan rangka, bracket, dan komponen sekunder bangunan.'],
                    ['nama' => 'Plat Hitam Tebal (14–50 mm)', 'deskripsi' => 'Untuk konstruksi berat seperti tangki, jembatan, dan kolom baja besar yang memerlukan kekuatan lentur dan tarik tinggi.'],
                    ['nama' => 'Plat Hitam Extra Tebal (>50 mm)', 'deskripsi' => 'Untuk aplikasi khusus seperti fondasi mesin berat, penahan benturan, dan komponen struktural dengan beban ekstrem.'],
                ],
                'keunggulan' => [
                    'Tersedia ketebalan 3 mm hingga 100 mm',
                    'Lebar hingga 2500 mm dan panjang hingga 12000 mm',
                    'Sifat mekanik homogen hasil hot rolling',
                    'Kemampuan las yang sangat baik',
                    'Material ASTM A36 / JIS G3101 berkualitas',
                    'Bisa dipotong custom sesuai kebutuhan proyek',
                ],
                'ukuran_intro' => 'Plat hitam tersedia dalam berbagai ketebalan. Dimensi standar lebar 1200 mm dan 2400 mm, namun tersedia juga ukuran custom.',
                'tabel_header' => ['Tebal (mm)', 'Lebar Standar (mm)', 'Panjang Standar (mm)', 'Berat (kg/lembar)', 'Grade'],
                'tabel_data'   => [
                    ['3',  '1200', '2400', '67,8',  'A36 / SS400'],
                    ['4',  '1200', '2400', '90,4',  'A36 / SS400'],
                    ['6',  '1200', '2400', '135,6', 'A36 / SS400'],
                    ['8',  '1200', '2400', '180,9', 'A36 / SS400'],
                    ['10', '1200', '2400', '226,1', 'A36 / SS400'],
                    ['12', '1200', '2400', '271,3', 'A36 / SS400'],
                    ['16', '1200', '2400', '361,7', 'A36 / SS400'],
                    ['20', '1500', '6000', '1413',  'A36 / SS400'],
                    ['25', '1500', '6000', '1766',  'A36 / SS400'],
                ],
                'kesimpulan' => 'Plat hitam adalah material baja lembaran yang serbaguna dan fundamental dalam industri fabrikasi dan konstruksi berat. Dengan memilih ketebalan yang sesuai kebutuhan teknis, efisiensi material dan keamanan struktur dapat terjamin. Selain itu, kemampuan las dan pembentukan yang baik menjadikan plat hitam material pilihan utama di berbagai sektor industri.',
                'spesifikasi' => ['Standar' => 'ASTM A36 / JIS G3101', 'Grade' => 'SS400 / A36', 'Tebal' => '3 – 100 mm', 'Lebar' => 'hingga 2500 mm', 'Panjang' => 'hingga 12000 mm'],
            ],

            // ─── PLAT BORDES ─────────────────────────────────────────────
            'plat-bordes' => [
                'name'      => 'Plat Bordes',
                'title'     => 'Plat Bordes (Checker Plate) – Pengertian, Fungsi, Ukuran',
                'subtitle'  => 'Plat baja dengan pola timbul anti-selip untuk lantai tangga, dek kendaraan, dan platform industri.',
                'category'  => 'Plat & Sheet',
                'icon'      => '⊞',
                'intro'     => 'Plat bordes atau checker plate adalah plat baja dengan permukaan bertekstur timbul yang berfungsi sebagai anti-selip. Material ini sangat penting untuk keselamatan di area yang dilalui manusia atau kendaraan. Karena itu, plat bordes banyak digunakan pada tangga, platform, dek kendaraan, dan area industri yang memerlukan pijakan aman. Selain itu, motif timbulnya juga memberikan estetika tersendiri pada konstruksi baja.',
                'pengertian'=> 'Plat bordes adalah plat baja hot-rolled dengan pola timbul (raised pattern) pada permukaannya yang berfungsi menambah koefisien gesekan sehingga mengurangi risiko tergelincir. Pola timbul umumnya berbentuk diamond (berlian), titik-titik, atau 5-bar. Dengan demikian, plat bordes tidak hanya fungsional tetapi juga estetis. Selain itu, material dasarnya sama dengan plat hitam sehingga memiliki kekuatan struktural yang baik.',
                'fungsi'    => [
                    ['judul' => 'Lantai tangga baja dan bordes', 'isi' => 'Aplikasi utama plat bordes adalah sebagai anak tangga dan platform tangga baja karena pola timbulnya mencegah tergelincir, bahkan saat basah atau terkena oli.'],
                    ['judul' => 'Dek kendaraan dan flatbed truck', 'isi' => 'Bak truck dan kendaraan angkut menggunakan plat bordes sebagai lantai dek untuk mencegah muatan dan orang tergelincir saat bongkar muat.'],
                    ['judul' => 'Platform dan catwalk industri', 'isi' => 'Di pabrik dan fasilitas industri, plat bordes digunakan sebagai platform kerja, catwalk, dan mezzanine floor yang aman untuk pekerja.'],
                    ['judul' => 'Penutup selokan dan manhole', 'isi' => 'Plat bordes tebal digunakan sebagai tutup selokan, manhole cover, dan trench cover di jalan dan area industri karena kekuatan dan anti-selipnya.'],
                ],
                'jenis'     => [
                    ['nama' => 'Pola Diamond (Berlian)', 'deskripsi' => 'Motif berlian atau ketupat yang paling umum. Memberikan traksi yang baik pada semua arah dan tampilan estetis yang bersih.'],
                    ['nama' => 'Pola 5-Bar', 'deskripsi' => 'Lima batang timbul yang tersusun diagonal. Memberikan kekakuan tambahan pada plat dan traksi yang sangat baik untuk aplikasi berat.'],
                    ['nama' => 'Pola Titik-titik (Dot Pattern)', 'deskripsi' => 'Tonjolan berbentuk titik bulat yang tersebar merata. Sering digunakan pada aplikasi dekoratif dan area pejalan kaki ringan.'],
                ],
                'keunggulan' => [
                    'Pola timbul anti-selip meningkatkan keselamatan',
                    'Tersedia ketebalan 3 mm hingga 12 mm',
                    'Lebar standar 1000 mm, 1200 mm, dan 1500 mm',
                    'Kekuatan struktural setara plat hitam',
                    'Tersedia dalam baja hitam, galvanis, dan stainless',
                    'Mudah dipotong dan difabrikasi sesuai kebutuhan',
                ],
                'ukuran_intro' => 'Plat bordes tersedia dalam berbagai ketebalan plat dasar (base thickness). Tinggi pola timbul tidak termasuk dalam dimensi tebal.',
                'tabel_header' => ['Tebal (mm)', 'Lebar (mm)', 'Panjang (mm)', 'Pola', 'Material'],
                'tabel_data'   => [
                    ['3',  '1000', '2000', 'Diamond / 5-bar', 'Baja Hitam'],
                    ['4',  '1200', '2400', 'Diamond / 5-bar', 'Baja Hitam'],
                    ['5',  '1200', '2400', 'Diamond / 5-bar', 'Baja Hitam'],
                    ['6',  '1200', '2400', 'Diamond / 5-bar', 'Baja Hitam / Galvanis'],
                    ['8',  '1500', '3000', 'Diamond / 5-bar', 'Baja Hitam'],
                    ['10', '1500', '3000', 'Diamond / 5-bar', 'Baja Hitam'],
                    ['12', '1500', '6000', 'Diamond / 5-bar', 'Baja Hitam'],
                ],
                'kesimpulan' => 'Plat bordes adalah solusi fungsional sekaligus estetis untuk lantai industri, tangga, dan platform yang membutuhkan keamanan anti-selip. Dengan memilih ketebalan dan pola yang sesuai kebutuhan, keselamatan dan daya tahan lantai dapat terjamin. Selain itu, ketersediaan dalam berbagai dimensi dan material memudahkan penyesuaian dengan desain konstruksi.',
                'spesifikasi' => ['Standar' => 'JIS G3101 / SNI', 'Tebal' => '3 – 12 mm', 'Pola' => 'Diamond / 5-bar', 'Lebar' => '1000 – 1500 mm', 'Finish' => 'Hitam / Galvanis'],
            ],

            // ─── PIPA GALVANIS ────────────────────────────────────────────
            'pipa-galvanis' => [
                'name'      => 'Pipa Galvanis',
                'title'     => 'Pipa Galvanis – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Pipa baja berlapis zinc untuk instalasi air, gas, scaffolding, dan konstruksi tahan karat.',
                'category'  => 'Pipa',
                'icon'      => 'O',
                'intro'     => 'Pipa galvanis adalah pipa baja yang telah dilapisi zinc melalui proses hot-dip galvanizing untuk memberikan perlindungan terhadap korosi. Material ini banyak digunakan pada instalasi air bersih, gas, scaffolding, dan berbagai aplikasi yang memerlukan ketahanan terhadap karat. Karena itu, pipa galvanis menjadi pilihan utama untuk konstruksi yang terekspos lingkungan lembab. Selain itu, lapisan zinc-nya memberikan daya tahan yang jauh lebih lama dibanding pipa baja tanpa pelindung.',
                'pengertian'=> 'Pipa galvanis adalah pipa baja karbon yang permukaannya dilapisi zinc melalui proses galvanisasi celup panas (hot-dip galvanizing) atau elektrogalvanisasi. Lapisan zinc bertindak sebagai pelindung katodik yang mencegah besi bereaksi dengan oksigen dan air. Dengan demikian, pipa galvanis memiliki umur pakai jauh lebih panjang dibanding pipa baja biasa di lingkungan korosif. Selain itu, permukaan zinc memberikan daya rekat yang baik untuk cat dan pelapisan tambahan.',
                'fungsi'    => [
                    ['judul' => 'Instalasi pipa air bersih', 'isi' => 'Pipa galvanis digunakan untuk distribusi air bersih pada bangunan komersial dan industri. Lapisan zinc mencegah korosi dari dalam yang dapat mencemari air.'],
                    ['judul' => 'Scaffolding dan perancah', 'isi' => 'Pipa galvanis diameter 48,3 mm (1½") adalah standar global untuk scaffolding bangunan. Lapisan galvanis melindungi pipa dari karat akibat paparan cuaca.'],
                    ['judul' => 'Instalasi gas dan pipa udara tekan', 'isi' => 'Untuk jaringan gas industri dan sistem udara tekan (compressed air), pipa galvanis digunakan karena ketahanan korosi dan kekuatannya yang memadai.'],
                    ['judul' => 'Pagar dan railing', 'isi' => 'Pipa galvanis banyak digunakan untuk pagar halaman, railing tangga, dan handrail karena tahan karat dan tidak memerlukan perawatan cat yang sering.'],
                ],
                'jenis'     => [
                    ['nama' => 'Pipa Galvanis Medium (B)', 'deskripsi' => 'Kelas medium untuk instalasi air dan gas bertekanan rendah hingga menengah. Tebal dinding lebih besar dari kelas light, cocok untuk penggunaan umum.'],
                    ['nama' => 'Pipa Galvanis Light (A)', 'deskripsi' => 'Kelas ringan dengan tebal dinding lebih tipis, cocok untuk scaffolding, pagar, dan instalasi tekanan rendah.'],
                    ['nama' => 'Pipa Galvanis Heavy (C)', 'deskripsi' => 'Kelas berat dengan tebal dinding paling tebal, untuk instalasi bertekanan tinggi dan aplikasi struktural yang memerlukan kekuatan lebih.'],
                ],
                'keunggulan' => [
                    'Lapisan zinc hot-dip memberikan proteksi korosi jangka panjang',
                    'Tersedia diameter ½" hingga 6" (nominal pipe size)',
                    'Memenuhi standar JIS G3452 dan SNI',
                    'Cocok untuk instalasi air, gas, scaffolding, dan pagar',
                    'Permukaan zinc mudah dicat untuk tampilan estetis',
                    'Umur pakai jauh lebih panjang dari pipa baja biasa',
                ],
                'ukuran_intro' => 'Pipa galvanis tersedia dalam berbagai ukuran nominal (NPS). Panjang standar 6 meter per batang.',
                'tabel_header' => ['Diameter Nominal', 'OD (mm)', 'Tebal (mm)', 'Berat (kg/m)', 'Panjang'],
                'tabel_data'   => [
                    ['½"',   '21,3', '2,65', '1,27', '6m'],
                    ['¾"',   '26,7', '2,65', '1,56', '6m'],
                    ['1"',   '33,4', '3,38', '2,50', '6m'],
                    ['1¼"',  '42,2', '3,56', '3,39', '6m'],
                    ['1½"',  '48,3', '3,68', '4,05', '6m'],
                    ['2"',   '60,3', '3,91', '5,44', '6m'],
                    ['2½"',  '76,1', '5,16', '9,12', '6m'],
                    ['3"',   '88,9', '5,49', '11,3', '6m'],
                    ['4"',   '114,3','6,02', '16,1', '6m'],
                    ['6"',   '168,3','7,11', '28,3', '6m'],
                ],
                'kesimpulan' => 'Pipa galvanis adalah solusi perpipaan yang andal dan tahan lama untuk berbagai aplikasi di lingkungan korosif. Dengan memilih kelas (light/medium/heavy) dan diameter yang sesuai kebutuhan tekanan dan aliran, instalasi dapat berjalan optimal. Selain itu, lapisan zinc hot-dip memastikan perlindungan korosi jangka panjang yang meminimalkan biaya perawatan.',
                'spesifikasi' => ['Standar' => 'JIS G3452 / SNI', 'Diameter' => '½" – 6"', 'Kelas' => 'Light / Medium / Heavy', 'Panjang' => '6m standar', 'Lapisan' => 'Hot-Dip Zinc'],
            ],

            // ─── PIPA STAINLESS ──────────────────────────────────────────
            'pipa-stainless' => [
                'name'      => 'Pipa Stainless Steel',
                'title'     => 'Pipa Stainless Steel – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Pipa baja tahan karat untuk industri makanan, farmasi, kimia, dan aplikasi higienis.',
                'category'  => 'Pipa',
                'icon'      => '◯',
                'intro'     => 'Pipa stainless steel adalah pipa baja paduan dengan kandungan kromium minimal 10,5% yang memberikan ketahanan korosi alami tanpa memerlukan pelapisan tambahan. Material ini wajib digunakan pada industri makanan, farmasi, kimia, dan aplikasi higienis yang tidak bisa menggunakan baja biasa. Karena itu, pipa stainless steel menjadi standar dalam industri yang memerlukan higienitas tinggi. Selain itu, penampilan permukaannya yang mengkilap memberikan nilai estetis pada aplikasi arsitektur.',
                'pengertian'=> 'Pipa stainless steel adalah pipa baja tahan karat (corrosion-resistant steel) yang mengandung setidaknya 10,5% kromium. Kandungan kromium ini membentuk lapisan oksida pasif (passive film) di permukaan yang melindungi baja dari korosi. Dengan demikian, pipa stainless steel tidak berkarat bahkan di lingkungan yang sangat korosif. Selain itu, sifatnya yang tidak reaktif membuatnya aman untuk kontak langsung dengan makanan dan bahan farmasi.',
                'fungsi'    => [
                    ['judul' => 'Instalasi industri makanan dan minuman', 'isi' => 'Standar wajib untuk pipa di pabrik pengolahan makanan, minuman, dan dairy karena tidak bereaksi dengan produk dan mudah dibersihkan (hygienic design).'],
                    ['judul' => 'Sistem perpipaan industri kimia', 'isi' => 'Grade SS316 dengan kandungan molibdenum digunakan untuk pipa di lingkungan kimia agresif, asam, dan larutan klorida yang akan merusak pipa baja biasa.'],
                    ['judul' => 'Railing dan handrail arsitektur', 'isi' => 'Pipa stainless steel dengan finish mirror atau hairline banyak digunakan sebagai railing tangga, handrail, dan elemen dekoratif pada bangunan modern.'],
                    ['judul' => 'Instalasi medis dan farmasi', 'isi' => 'Di rumah sakit dan pabrik farmasi, pipa stainless digunakan untuk sistem distribusi gas medis, air steril, dan media produksi yang memerlukan higienitas tinggi.'],
                ],
                'jenis'     => [
                    ['nama' => 'SS304 (18/8 Stainless)', 'deskripsi' => 'Grade paling umum dengan 18% Cr dan 8% Ni. Tahan terhadap korosi atmosfer dan bahan kimia ringan. Cocok untuk aplikasi food grade dan arsitektur.'],
                    ['nama' => 'SS316 (Marine Grade)', 'deskripsi' => 'Mengandung molibdenum 2-3% untuk ketahanan lebih baik terhadap klorida dan lingkungan marine. Ideal untuk industri kimia dan lingkungan laut.'],
                    ['nama' => 'SS201 (Economy Grade)', 'deskripsi' => 'Grade ekonomis dengan mangan sebagai pengganti sebagian nikel. Ketahanan korosi lebih rendah dari SS304, cocok untuk aplikasi dekoratif indoor.'],
                ],
                'keunggulan' => [
                    'Ketahanan korosi alami tanpa pelapisan tambahan',
                    'Hygienic – aman kontak langsung dengan makanan',
                    'Tersedia grade SS201, SS304, dan SS316',
                    'Berbagai pilihan finish: 2B, Hairline, Mirror Polish',
                    'Kekuatan mekanik yang baik pada suhu tinggi',
                    'Estetis dan mudah dibersihkan',
                ],
                'ukuran_intro' => 'Pipa stainless steel tersedia dalam berbagai ukuran dan schedule (ketebalan dinding). Panjang standar 6 meter.',
                'tabel_header' => ['Diameter (inch)', 'OD (mm)', 'Tebal (mm)', 'Grade', 'Finish'],
                'tabel_data'   => [
                    ['½"',  '21,3', '1,65 – 3,73', 'SS304 / SS316', '2B / Hairline'],
                    ['¾"',  '26,7', '1,65 – 3,91', 'SS304 / SS316', '2B / Hairline'],
                    ['1"',  '33,4', '1,65 – 4,55', 'SS304 / SS316', '2B / Hairline'],
                    ['2"',  '60,3', '1,65 – 5,54', 'SS304 / SS316', '2B / Hairline'],
                    ['3"',  '88,9', '2,11 – 7,62', 'SS304 / SS316', '2B'],
                    ['4"',  '114,3','2,11 – 8,56', 'SS304 / SS316', '2B'],
                    ['6"',  '168,3','2,77 – 10,97','SS304 / SS316', '2B'],
                ],
                'kesimpulan' => 'Pipa stainless steel adalah solusi perpipaan premium untuk industri yang memerlukan ketahanan korosi tinggi, higienitas, dan estetika. Dengan memilih grade yang sesuai kondisi lingkungan, performa dan umur pakai instalasi dapat dimaksimalkan. Selain itu, biaya perawatan yang rendah menjadikan investasi pada pipa stainless steel sangat menguntungkan dalam jangka panjang.',
                'spesifikasi' => ['Grade' => 'SS201 / SS304 / SS316', 'Diameter' => '¼" – 12"', 'Finish' => '2B / Hairline / Mirror', 'Standar' => 'ASTM A312', 'Panjang' => '6m standar'],
            ],

            // ─── HOLLOW HITAM ────────────────────────────────────────────
            'hollow-hitam' => [
                'name'      => 'Hollow Hitam',
                'title'     => 'Hollow Hitam (SHS/RHS) – Pengertian, Fungsi, Ukuran',
                'subtitle'  => 'Hollow baja hitam profil persegi dan persegi panjang untuk rangka bangunan, kanopi, dan furniture metal.',
                'category'  => 'Hollow',
                'icon'      => '□',
                'intro'     => 'Hollow hitam atau besi hollow adalah profil baja berongga berbentuk persegi (SHS) atau persegi panjang (RHS) yang banyak digunakan pada konstruksi rangka ringan, kanopi, pagar, dan furniture metal. Material ini menawarkan kekuatan yang baik dengan penampilan yang rapi dan bersih. Karena itu, hollow hitam menjadi pilihan utama untuk konstruksi yang terlihat secara estetis. Selain itu, kemudahan pemotongan dan pengelasan menjadikannya sangat fleksibel di lapangan.',
                'pengertian'=> 'Hollow hitam adalah profil baja cold-formed berongga dengan penampang persegi (Square Hollow Section/SHS) atau persegi panjang (Rectangular Hollow Section/RHS). Profil ini dihasilkan dari strip baja yang dibentuk dan dilas memanjang. Dengan demikian, hollow hitam memiliki distribusi material yang efisien dan rasio kekuatan terhadap berat yang baik. Selain itu, permukaan yang rata dan sudut yang presisi memudahkan perakitan dan finishing.',
                'fungsi'    => [
                    ['judul' => 'Rangka kanopi dan carport', 'isi' => 'Hollow hitam adalah material utama untuk konstruksi kanopi, carport, dan pergola karena penampilan yang rapi, ringan, dan mudah difabrikasi.'],
                    ['judul' => 'Pagar dan railing baja', 'isi' => 'Kombinasi hollow besar sebagai tiang dan hollow kecil sebagai balustra membuat pagar baja yang kokoh, estetis, dan tahan lama.'],
                    ['judul' => 'Rangka furniture dan interior metal', 'isi' => 'Industri mebel dan interior menggunakan hollow hitam untuk rangka meja, kursi, rak, dan partisi karena kemudahan pembentukan dan tampilan modern.'],
                    ['judul' => 'Konstruksi rangka ringan dan mezanin', 'isi' => 'Rangka bangunan non-struktural, partisi, dan mezanin floor menggunakan hollow hitam sebagai kolom dan balok sekunder yang efisien.'],
                ],
                'jenis'     => [
                    ['nama' => 'SHS (Square Hollow Section)', 'deskripsi' => 'Penampang persegi dengan semua sisi sama panjang. Sering digunakan sebagai kolom kecil, tiang pagar, dan rangka yang memerlukan tampilan simetris.'],
                    ['nama' => 'RHS (Rectangular Hollow Section)', 'deskripsi' => 'Penampang persegi panjang dengan dua sisi yang berbeda panjang. Efisien sebagai balok karena momen inersia yang lebih besar pada sumbu kuat.'],
                    ['nama' => 'Hollow Hitam Cat Powder Coating', 'deskripsi' => 'Hollow hitam dengan lapisan cat powder coating aneka warna untuk finishing akhir yang tahan lama, estetis, dan tahan gores pada aplikasi furniture dan pagar.'],
                ],
                'keunggulan' => [
                    'Penampilan rapi dengan sudut tajam dan permukaan halus',
                    'Tersedia ukuran 20×20 mm hingga 200×200 mm',
                    'Tebal dinding 1,6 mm hingga 6,0 mm',
                    'Mudah dipotong, dibor, dan dilas di lapangan',
                    'Rasio kekuatan terhadap berat yang efisien',
                    'Ready stock berbagai ukuran dengan pengiriman cepat',
                ],
                'ukuran_intro' => 'Hollow hitam tersedia dalam berbagai ukuran SHS dan RHS. Panjang standar 6 meter per batang.',
                'tabel_header' => ['Ukuran (mm)', 'Tebal (mm)', 'Berat (kg/m)', 'Tipe', 'Panjang'],
                'tabel_data'   => [
                    ['20 × 20',   '1,6', '0,88', 'SHS', '6m'],
                    ['25 × 25',   '1,6', '1,12', 'SHS', '6m'],
                    ['40 × 40',   '2,0', '2,31', 'SHS', '6m'],
                    ['50 × 50',   '2,0', '2,93', 'SHS', '6m'],
                    ['50 × 100',  '2,0', '4,39', 'RHS', '6m'],
                    ['60 × 120',  '3,0', '8,00', 'RHS', '6m'],
                    ['100 × 100', '4,0', '12,0', 'SHS', '6m'],
                    ['150 × 150', '6,0', '26,8', 'SHS', '6m'],
                    ['200 × 200', '6,0', '36,2', 'SHS', '6m'],
                ],
                'kesimpulan' => 'Hollow hitam adalah profil baja serbaguna yang ideal untuk konstruksi ringan, furniture, dan aplikasi arsitektur. Dengan memilih ukuran dan tebal yang sesuai beban, efisiensi material dan estetika dapat dicapai bersamaan. Selain itu, kemudahan fabrikasi dan ketersediaan berbagai ukuran menjadikan hollow hitam salah satu produk baja paling populer di pasar konstruksi.',
                'spesifikasi' => ['Standar' => 'JIS G3466 / SNI', 'Ukuran' => '20×20 – 200×200 mm', 'Tebal' => '1,6 – 6,0 mm', 'Panjang' => '6m standar', 'Tipe' => 'SHS / RHS'],
            ],

            // ─── HOLLOW GALVALUM ─────────────────────────────────────────
            'hollow-galvalum' => [
                'name'      => 'Hollow Galvalum',
                'title'     => 'Hollow Galvalum – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Hollow baja ringan galvalum untuk rangka atap, plafon, dan partisi yang ringan dan tahan karat.',
                'category'  => 'Baja Ringan',
                'icon'      => '⊡',
                'intro'     => 'Hollow galvalum adalah profil hollow baja ringan yang dilapisi campuran aluminium dan zinc (Al-Zn coating) untuk ketahanan korosi yang sangat baik. Material ini banyak digunakan untuk rangka atap, plafon, dan partisi pada sistem konstruksi baja ringan modern. Karena itu, hollow galvalum menjadi alternatif populer untuk hollow baja hitam pada aplikasi yang rentan terhadap kelembapan. Selain itu, bobotnya yang ringan mempercepat proses instalasi.',
                'pengertian'=> 'Hollow galvalum adalah profil berongga baja ringan dengan lapisan galvalum (55% aluminium + 43,5% zinc + 1,5% silikon). Lapisan ini memberikan ketahanan korosi yang lebih baik dibanding galvanisasi biasa, bahkan di lingkungan lembab dan pantai. Dengan demikian, hollow galvalum memiliki umur pakai yang lebih panjang untuk aplikasi outdoor dan semi-outdoor. Selain itu, beratnya yang jauh lebih ringan dari hollow baja biasa mengurangi beban struktur secara keseluruhan.',
                'fungsi'    => [
                    ['judul' => 'Rangka plafon gypsum dan GRC', 'isi' => 'Hollow galvalum adalah rangka utama untuk plafon gypsum board dan GRC pada bangunan komersial dan residensial, karena ringan dan tahan terhadap kelembapan ruangan.'],
                    ['judul' => 'Rangka dinding partisi', 'isi' => 'Digunakan sebagai stud dan runner untuk dinding partisi gypsum di perkantoran, hotel, dan rumah sakit yang memerlukan sekat fleksibel dan ringan.'],
                    ['judul' => 'Rangka kanopi dan carport ringan', 'isi' => 'Untuk kanopi non-struktural dan carport, hollow galvalum memberikan kombinasi ringan dan tahan karat yang ideal, terutama di daerah dengan curah hujan tinggi.'],
                    ['judul' => 'Rangka backdrop dan display', 'isi' => 'Industri pameran dan interior menggunakan hollow galvalum untuk rangka backdrop, display booth, dan elemen dekoratif yang memerlukan presisi dan kebersihan material.'],
                ],
                'jenis'     => [
                    ['nama' => 'Hollow Galvalum Standar', 'deskripsi' => 'Tebal 0,6–0,75 mm untuk aplikasi plafon dan partisi ringan yang tidak menerima beban besar. Paling populer untuk interior bangunan.'],
                    ['nama' => 'Hollow Galvalum Medium', 'deskripsi' => 'Tebal 1,0–1,2 mm untuk rangka atap ringan, kanopi, dan aplikasi semi-struktural yang memerlukan kekuatan lebih baik.'],
                    ['nama' => 'Hollow Galvalum Heavy', 'deskripsi' => 'Tebal 1,5–2,0 mm untuk aplikasi yang memerlukan kekuatan lebih besar, seperti rangka atap bentang lebar dan konstruksi baja ringan komersial.'],
                ],
                'keunggulan' => [
                    'Lapisan Al-Zn tahan korosi lebih baik dari galvanis biasa',
                    'Bobot ringan mempercepat instalasi dan mengurangi beban',
                    'Dimensi presisi hasil cold-forming',
                    'Tersedia ukuran 25×50 mm hingga 75×75 mm',
                    'Tidak berkarat bahkan di lingkungan lembab',
                    'Ramah lingkungan dan dapat didaur ulang',
                ],
                'ukuran_intro' => 'Hollow galvalum tersedia dalam berbagai ukuran dengan panjang standar 4 meter dan 6 meter.',
                'tabel_header' => ['Ukuran (mm)', 'Tebal (mm)', 'Berat (kg/m)', 'Coating', 'Panjang'],
                'tabel_data'   => [
                    ['20 × 40',  '0,60', '0,55', 'Galvalum AZ150', '4m / 6m'],
                    ['25 × 50',  '0,60', '0,68', 'Galvalum AZ150', '4m / 6m'],
                    ['40 × 40',  '0,75', '0,88', 'Galvalum AZ150', '4m / 6m'],
                    ['40 × 60',  '0,75', '1,05', 'Galvalum AZ150', '4m / 6m'],
                    ['50 × 50',  '1,00', '1,47', 'Galvalum AZ150', '4m / 6m'],
                    ['50 × 100', '1,00', '2,21', 'Galvalum AZ150', '4m / 6m'],
                    ['75 × 75',  '1,20', '2,65', 'Galvalum AZ150', '4m / 6m'],
                ],
                'kesimpulan' => 'Hollow galvalum adalah solusi rangka modern yang ringan, tahan karat, dan efisien untuk plafon, partisi, dan konstruksi baja ringan. Dengan lapisan galvalum yang superior, material ini memberikan umur pakai panjang dengan perawatan minimal. Selain itu, bobotnya yang ringan signifikan mengurangi beban mati struktur dan mempercepat proses konstruksi.',
                'spesifikasi' => ['Material' => 'Galvalum AZ150', 'Ukuran' => '20×40 – 75×75 mm', 'Tebal' => '0,6 – 2,0 mm', 'Panjang' => '4m / 6m', 'Coating' => 'Al-Zn 55%'],
            ],

            // ─── ATAP GALVALUM ───────────────────────────────────────────
            'atap-galvalum' => [
                'name'      => 'Atap Galvalum',
                'title'     => 'Atap Galvalum – Pengertian, Fungsi, Jenis, Ukuran Standar',
                'subtitle'  => 'Atap baja ringan galvalum untuk bangunan hunian, pabrik, dan gudang. Ringan, kuat, dan tahan karat.',
                'category'  => 'Baja Ringan',
                'icon'      => '∧',
                'intro'     => 'Atap galvalum adalah material penutup atap dari baja ringan yang dilapisi campuran aluminium-zinc (Zincalume) yang memberikan ketahanan korosi tinggi. Material ini sangat populer di Indonesia sebagai pengganti atap asbes, genteng beton, maupun seng biasa. Karena itu, atap galvalum banyak digunakan pada bangunan hunian, pabrik, gudang, dan bangunan komersial. Selain itu, bobotnya yang ringan mengurangi beban struktur atap secara signifikan.',
                'pengertian'=> 'Atap galvalum adalah lembaran baja ringan bergelombang yang dilapisi galvalum (55% aluminium, 43,5% zinc, 1,5% silicon). Profil bergelombang meningkatkan kekakuan lembaran sehingga mampu menopang beban atap dengan tebal material yang tipis. Dengan demikian, atap galvalum memiliki rasio kekuatan terhadap berat yang sangat baik. Selain itu, lapisan galvalum memberikan ketahanan korosi yang jauh lebih baik dibanding seng galvanis biasa.',
                'fungsi'    => [
                    ['judul' => 'Penutup atap bangunan hunian', 'isi' => 'Atap galvalum menggantikan genteng dan asbes pada rumah tinggal, kos, dan perumahan karena ringan, tahan lama, dan tidak memerlukan rangka yang kuat.'],
                    ['judul' => 'Atap pabrik dan gudang industri', 'isi' => 'Bangunan industri skala besar menggunakan atap galvalum karena kemampuannya menutup bentang lebar, ringan, dan tahan terhadap cuaca ekstrem.'],
                    ['judul' => 'Kanopi dan carport', 'isi' => 'Atap galvalum digunakan sebagai penutup kanopi, carport, dan shelter yang memerlukan material ringan, tahan hujan, dan pemasangan cepat.'],
                    ['judul' => 'Renovasi dan pelapisan ulang atap', 'isi' => 'Atap galvalum dapat dipasang di atas atap lama yang masih kokoh sebagai lapisan baru, menghemat biaya pembongkaran dan memperpanjang umur atap.'],
                ],
                'jenis'     => [
                    ['nama' => 'Galvalum Gelombang (Corrugated)', 'deskripsi' => 'Profil bergelombang sinus standar. Paling umum digunakan untuk gudang, pabrik, dan kanopi. Mudah dipasang dan harga ekonomis.'],
                    ['nama' => 'Galvalum Spandek', 'deskripsi' => 'Profil trapesoid dengan pola kecil yang rapat. Memberikan tampilan lebih rapi dan modern, populer untuk bangunan komersial dan perumahan.'],
                    ['nama' => 'Galvalum Sakura / Standing Seam', 'deskripsi' => 'Profil dengan locking system yang mencegah kebocoran. Ideal untuk bangunan dengan kemiringan atap rendah dan estetika tinggi.'],
                ],
                'keunggulan' => [
                    'Bobot sangat ringan (5–7 kg/m²) mengurangi beban struktur',
                    'Lapisan Al-Zn tahan korosi 4× lebih baik dari seng biasa',
                    'Tersedia tebal 0,25 mm hingga 0,50 mm',
                    'Panjang custom sesuai kebutuhan, bisa hingga 15 meter',
                    'Pemasangan cepat dan mudah dengan screw self-drilling',
                    'Memantulkan panas matahari, mengurangi panas di dalam ruangan',
                ],
                'ukuran_intro' => 'Atap galvalum tersedia dalam berbagai tebal dan profil. Panjang dapat dipotong sesuai pesanan.',
                'tabel_header' => ['Profil', 'Tebal (mm BMT)', 'Lebar Efektif (mm)', 'Berat (kg/m²)', 'Panjang'],
                'tabel_data'   => [
                    ['Corrugated',   '0,25', '760', '2,20', 'Custom'],
                    ['Corrugated',   '0,30', '760', '2,65', 'Custom'],
                    ['Spandek',      '0,30', '900', '2,75', 'Custom'],
                    ['Spandek',      '0,35', '900', '3,20', 'Custom'],
                    ['Spandek',      '0,40', '900', '3,65', 'Custom'],
                    ['Sakura',       '0,40', '800', '3,70', 'Custom'],
                    ['Standing Seam','0,50', '500', '4,60', 'Custom'],
                ],
                'kesimpulan' => 'Atap galvalum adalah pilihan penutup atap modern yang efisien, tahan lama, dan ekonomis untuk berbagai jenis bangunan. Dengan lapisan galvalum yang superior, material ini memberikan perlindungan terhadap korosi dalam jangka panjang tanpa perawatan khusus. Selain itu, bobotnya yang ringan secara signifikan mengurangi beban dan biaya struktur atap.',
                'spesifikasi' => ['Material' => 'Galvalum AZ150', 'Tebal' => '0,25 – 0,50 mm', 'Lebar' => '760 – 1000 mm', 'Panjang' => 'Custom Order', 'Profil' => 'Corrugated / Spandek'],
            ],

            // ─── CANAL GALVALUM ──────────────────────────────────────────
            'canal-galvalum' => [
                'name'      => 'Canal Galvalum',
                'title'     => 'Canal Galvalum (CNP) – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Kanal C baja ringan galvalum untuk gording, reng, dan rangka atap sistem baja ringan modern.',
                'category'  => 'Baja Ringan',
                'icon'      => 'C',
                'intro'     => 'Canal galvalum adalah profil kanal C dari baja ringan berlapisan galvalum yang digunakan sebagai gording, purlin, dan reng pada sistem konstruksi atap baja ringan. Material ini menggabungkan kekuatan struktural dengan ketahanan korosi tinggi dari lapisan Al-Zn. Karena itu, canal galvalum menjadi komponen utama dalam sistem rangka atap baja ringan modern. Selain itu, beratnya yang sangat ringan mempercepat proses instalasi secara signifikan.',
                'pengertian'=> 'Canal galvalum adalah profil C baja ringan cold-formed yang dilapisi galvalum (campuran aluminium 55% dan zinc 43,5%). Profil C dengan bibir (lips) pada kedua ujung sayap meningkatkan momen inersia dan kekakuan profil secara signifikan. Dengan demikian, canal galvalum mampu menopang beban atap dengan dimensi yang sangat ringan. Selain itu, lapisan galvalum memberikan perlindungan ganda terhadap korosi dari dalam maupun luar.',
                'fungsi'    => [
                    ['judul' => 'Gording atap baja ringan', 'isi' => 'Canal galvalum adalah gording utama yang dipasang di atas kuda-kuda baja ringan untuk menopang reng dan penutup atap. Jarak antar gording disesuaikan dengan jenis penutup atap.'],
                    ['judul' => 'Reng (batten) untuk atap metal', 'isi' => 'Canal galvalum ukuran kecil digunakan sebagai reng yang menopang lembaran atap galvalum atau metal tile, dipasang tegak lurus pada gording.'],
                    ['judul' => 'Purlin dinding bangunan industri', 'isi' => 'Sebagai girt (purlin dinding), canal galvalum dipasang horizontal di antara kolom untuk menopang dinding panel atau cladding bangunan industri.'],
                    ['judul' => 'Rangka mezanin dan platform ringan', 'isi' => 'Canal galvalum digunakan sebagai balok pada mezanin dan platform ringan yang tidak memerlukan struktur baja berat, memberikan solusi ekonomis.'],
                ],
                'jenis'     => [
                    ['nama' => 'Canal Galvalum Standar (G250)', 'deskripsi' => 'Grade G250 dengan tegangan leleh 250 MPa. Untuk gording dan purlin pada bangunan hunian dan bangunan komersial ringan.'],
                    ['nama' => 'Canal Galvalum High Tensile (G550)', 'deskripsi' => 'Grade G550 dengan tegangan leleh 550 MPa. Kekuatan lebih tinggi memungkinkan penggunaan tebal lebih tipis dengan kapasitas beban yang sama.'],
                    ['nama' => 'Canal Galvalum Berlapis Cat', 'deskripsi' => 'Canal galvalum dengan lapisan cat tambahan (pre-painted) untuk aplikasi yang memerlukan warna atau perlindungan ekstra terhadap lingkungan agresif.'],
                ],
                'keunggulan' => [
                    'Bobot sangat ringan mempercepat dan memudahkan instalasi',
                    'Lapisan galvalum tahan korosi di lingkungan lembab dan pantai',
                    'Tersedia grade G250 dan G550',
                    'Dimensi presisi hasil cold-forming untuk kualitas konsisten',
                    'Mudah dipotong dan disambung dengan screw atau baut',
                    'Ramah lingkungan dan dapat didaur ulang 100%',
                ],
                'ukuran_intro' => 'Canal galvalum tersedia dalam berbagai ukuran H×B sesuai kebutuhan beban. Panjang standar 6 meter.',
                'tabel_header' => ['Ukuran H×B (mm)', 'Tebal (mm)', 'Berat (kg/m)', 'Grade', 'Panjang'],
                'tabel_data'   => [
                    ['60 × 30',   '0,75', '0,72', 'G250', '6m'],
                    ['75 × 45',   '0,75', '0,92', 'G250', '6m'],
                    ['100 × 50',  '1,00', '1,43', 'G250 / G550', '6m'],
                    ['100 × 50',  '1,20', '1,72', 'G250 / G550', '6m'],
                    ['125 × 50',  '1,00', '1,65', 'G250 / G550', '6m'],
                    ['150 × 65',  '1,20', '2,47', 'G250 / G550', '6m'],
                    ['200 × 75',  '1,60', '4,35', 'G550', '6m'],
                ],
                'kesimpulan' => 'Canal galvalum adalah komponen struktural kunci dalam sistem rangka atap baja ringan modern. Dengan kombinasi kekuatan, ketahanan korosi, dan bobot yang ringan, material ini memberikan solusi atap yang efisien dan tahan lama. Selain itu, kemudahan instalasi dan tidak memerlukan perawatan menjadikan canal galvalum pilihan yang sangat ekonomis dalam jangka panjang.',
                'spesifikasi' => ['Material' => 'Galvalum AZ150', 'Grade' => 'G250 / G550', 'Ukuran' => '60×30 – 200×75 mm', 'Panjang' => '6m standar', 'Coating' => 'Al-Zn 55%'],
            ],

            // ─── WIREMESH ────────────────────────────────────────────────
            'wiremesh' => [
                'name'      => 'Wiremesh',
                'title'     => 'Wiremesh – Pengertian, Fungsi, Jenis, Ukuran SNI',
                'subtitle'  => 'Anyaman kawat las untuk tulangan pelat lantai, jalan, precast, dan konstruksi beton bertulang.',
                'category'  => 'Wiremesh',
                'icon'      => '⊞',
                'intro'     => 'Wiremesh adalah anyaman kawat baja las yang digunakan sebagai tulangan alternatif pada konstruksi beton bertulang, khususnya pelat lantai, jalan beton, dan elemen precast. Material ini menawarkan kemudahan dan kecepatan pemasangan yang jauh lebih tinggi dibanding tulangan besi beton batangan. Karena itu, wiremesh semakin populer pada proyek konstruksi berskala besar yang mengejar efisiensi waktu. Selain itu, konsistensi jarak antar kawat yang terjamin meningkatkan kualitas tulangan.',
                'pengertian'=> 'Wiremesh atau welded wire mesh adalah lembaran anyaman kawat baja yang titik-titik persilangannya dilas secara otomatis. Kawat dianyam membentuk grid dengan jarak antar kawat yang seragam pada kedua arah. Dengan demikian, distribusi tulangan dalam beton menjadi merata dan konsisten. Selain itu, lembaran wiremesh yang terstandar memudahkan quality control dan perhitungan kebutuhan material pada proyek konstruksi.',
                'fungsi'    => [
                    ['judul' => 'Tulangan pelat lantai beton', 'isi' => 'Aplikasi utama wiremesh adalah sebagai tulangan pada pelat lantai beton bangunan, menggantikan rangkaian besi beton satu per satu yang memakan waktu lebih lama.'],
                    ['judul' => 'Perkerasan jalan dan apron beton', 'isi' => 'Wiremesh digunakan sebagai tulangan temperature dan susut pada perkerasan jalan beton, landasan parkir, dan apron bandara untuk mencegah retak.'],
                    ['judul' => 'Elemen precast dan panel beton', 'isi' => 'Industri precast menggunakan wiremesh sebagai tulangan pada dinding panel beton, paving block, dan elemen beton pracetak lainnya.'],
                    ['judul' => 'Tulangan dinding bata dan plesteran', 'isi' => 'Wiremesh dipasang pada dinding bata sebagai tulangan tambahan untuk meningkatkan ketahanan terhadap retak, khususnya di daerah rawan gempa.'],
                ],
                'jenis'     => [
                    ['nama' => 'Wiremesh M4 – M6 (Ringan)', 'deskripsi' => 'Diameter kawat 4–6 mm untuk tulangan pelat lantai ringan, dinding, dan elemen non-struktural yang tidak menerima beban berat.'],
                    ['nama' => 'Wiremesh M7 – M10 (Standar)', 'deskripsi' => 'Diameter kawat 7–10 mm untuk tulangan pelat lantai standar, perkerasan jalan, dan elemen struktural ringan hingga menengah.'],
                    ['nama' => 'Wiremesh M12 – M16 (Berat)', 'deskripsi' => 'Diameter kawat 12–16 mm untuk pelat lantai yang menerima beban berat, pondasi, dan elemen precast struktural.'],
                ],
                'keunggulan' => [
                    'Pemasangan lebih cepat dibanding besi beton batangan',
                    'Jarak antar kawat konsisten sesuai standar SNI',
                    'Tersedia diameter M4 hingga M12',
                    'Ukuran sheet standar 2,1 m × 5,4 m',
                    'Mengurangi resiko kesalahan pemasangan tulangan',
                    'Menghemat tenaga kerja dan mempercepat jadwal proyek',
                ],
                'ukuran_intro' => 'Wiremesh tersedia dalam berbagai tipe berdasarkan diameter kawat. Ukuran sheet standar adalah 2,1 m × 5,4 m.',
                'tabel_header' => ['Tipe', 'Dia. Kawat (mm)', 'Jarak Kawat (mm)', 'Berat (kg/lembar)', 'Ukuran Sheet'],
                'tabel_data'   => [
                    ['M4',  '4',  '150 × 150', '12,7', '2,1 × 5,4 m'],
                    ['M5',  '5',  '150 × 150', '19,8', '2,1 × 5,4 m'],
                    ['M6',  '6',  '150 × 150', '28,5', '2,1 × 5,4 m'],
                    ['M7',  '7',  '150 × 150', '38,8', '2,1 × 5,4 m'],
                    ['M8',  '8',  '150 × 150', '50,7', '2,1 × 5,4 m'],
                    ['M9',  '9',  '150 × 150', '64,1', '2,1 × 5,4 m'],
                    ['M10', '10', '150 × 150', '79,2', '2,1 × 5,4 m'],
                    ['M12', '12', '150 × 150', '114',  '2,1 × 5,4 m'],
                ],
                'kesimpulan' => 'Wiremesh adalah solusi tulangan modern yang mengoptimalkan kecepatan konstruksi dan konsistensi kualitas. Dengan distribusi tulangan yang merata dan seragam, kinerja struktural pelat beton dapat dimaksimalkan. Selain itu, efisiensi pemasangan yang tinggi menjadikan wiremesh pilihan cerdas untuk proyek konstruksi yang mengejar jadwal ketat.',
                'spesifikasi' => ['Standar' => 'SNI 03-6812-2002', 'Tipe' => 'M4 – M12', 'Jarak Kawat' => '100×100 / 150×150 mm', 'Sheet' => '2,1 × 5,4 m', 'Material' => 'Baja karbon rendah'],
            ],

            // ─── PAGAR BRC ───────────────────────────────────────────────
            'pagar-brc' => [
                'name'      => 'Pagar BRC',
                'title'     => 'Pagar BRC – Pengertian, Fungsi, Jenis, Ukuran Standar',
                'subtitle'  => 'Pagar kawat las (welded mesh fence) untuk keamanan area pabrik, perumahan, sekolah, dan fasilitas umum.',
                'category'  => 'Pagar',
                'icon'      => '▦',
                'intro'     => 'Pagar BRC adalah sistem pagar dari kawat baja las berbentuk panel-panel yang mudah dipasang dan memberikan keamanan area yang handal. Material ini menjadi pilihan utama untuk pagar pabrik, perumahan, sekolah, rumah sakit, dan fasilitas umum yang memerlukan keamanan tanpa menghalangi visibilitas. Karena itu, pagar BRC sangat populer di Indonesia sebagai pengganti pagar dinding yang masif. Selain itu, desainnya yang bersih memberikan tampilan profesional pada berbagai properti.',
                'pengertian'=> 'Pagar BRC (British Reinforced Concrete) adalah panel pagar dari kawat baja las yang permukaannya dilapisi zinc melalui galvanisasi. Panel dibentuk dari kawat melintang dan memanjang yang dilas di setiap titik persimpangan menghasilkan grid yang kuat dan kaku. Dengan demikian, pagar BRC tahan terhadap tekanan mekanis dan tidak mudah dideformasi. Selain itu, lapisan galvanis memberikan ketahanan korosi untuk pemasangan outdoor jangka panjang.',
                'fungsi'    => [
                    ['judul' => 'Keamanan perimeter pabrik dan gudang', 'isi' => 'Pagar BRC dipasang mengelilingi kawasan industri untuk membatasi akses, mencegah pencurian, dan mendefinisikan batas properti secara jelas.'],
                    ['judul' => 'Pagar perumahan dan kompleks', 'isi' => 'Pada perumahan modern, pagar BRC digunakan sebagai pagar keliling yang memberikan keamanan tanpa menutup visibilitas, memberikan kesan terbuka namun aman.'],
                    ['judul' => 'Pembatas lapangan olahraga', 'isi' => 'Lapangan tenis, futsal, basket, dan olahraga lainnya menggunakan pagar BRC sebagai pembatas yang kuat dan aman bagi pemain dan penonton.'],
                    ['judul' => 'Pagar sekolah dan fasilitas publik', 'isi' => 'Sekolah, rumah sakit, dan fasilitas publik menggunakan pagar BRC untuk keamanan tanpa memberikan kesan tertutup dan mengintimidasi.'],
                ],
                'jenis'     => [
                    ['nama' => 'Pagar BRC Galvanis Standard', 'deskripsi' => 'Panel kawat las galvanis standar untuk kebutuhan umum. Tersedia tinggi 0,9 m hingga 2,4 m dengan berbagai pilihan ukuran kawat.'],
                    ['nama' => 'Pagar BRC Powder Coating', 'deskripsi' => 'Panel BRC galvanis dengan lapisan cat powder coating warna hijau atau hitam untuk tampilan yang lebih estetis dan ketahanan korosi ganda.'],
                    ['nama' => 'Pagar BRC Anti-Climb', 'deskripsi' => 'Panel dengan mesh rapat dan tonjolan pengaman di bagian atas untuk area keamanan tinggi yang mencegah pendakian dari luar.'],
                ],
                'keunggulan' => [
                    'Pemasangan cepat dengan sistem panel modular',
                    'Lapisan galvanis tahan korosi untuk outdoor jangka panjang',
                    'Tinggi tersedia 0,9 m – 2,4 m sesuai kebutuhan keamanan',
                    'Visibilitas terjaga, tidak menghalangi pandangan',
                    'Struktural kaku, tahan deformasi mekanis',
                    'Tersedia dalam varian galvanis dan powder coating',
                ],
                'ukuran_intro' => 'Pagar BRC tersedia dalam berbagai tinggi panel dan diameter kawat. Panjang panel standar 2,4 m atau 3,0 m.',
                'tabel_header' => ['Tinggi (mm)', 'Dia. Kawat (mm)', 'Mesh (mm)', 'Panjang Panel (m)', 'Finish'],
                'tabel_data'   => [
                    ['900',  '4',   '75 × 150',  '2,4 / 3,0', 'Galvanis'],
                    ['1200', '4',   '75 × 150',  '2,4 / 3,0', 'Galvanis'],
                    ['1500', '5',   '75 × 150',  '2,4 / 3,0', 'Galvanis / PC'],
                    ['1800', '5',   '75 × 150',  '2,4 / 3,0', 'Galvanis / PC'],
                    ['2000', '6',   '75 × 150',  '2,4 / 3,0', 'Galvanis / PC'],
                    ['2400', '6',   '75 × 150',  '2,4 / 3,0', 'Galvanis / PC'],
                ],
                'kesimpulan' => 'Pagar BRC adalah solusi keamanan area yang efektif, efisien, dan estetis untuk berbagai jenis properti. Dengan sistem panel modular, pemasangan dapat dilakukan cepat dan rapi. Selain itu, lapisan galvanis memastikan ketahanan jangka panjang tanpa perawatan intensif, menjadikan pagar BRC investasi keamanan yang sangat ekonomis.',
                'spesifikasi' => ['Standar' => 'SNI / BS', 'Dia. Kawat' => '4 – 6 mm', 'Tinggi' => '0,9 – 2,4 m', 'Panjang Panel' => '2,4 m / 3,0 m', 'Finish' => 'Galvanis / PC'],
            ],

            // ─── BONDEK ──────────────────────────────────────────────────
            'bondek' => [
                'name'      => 'Bondek',
                'title'     => 'Bondek (Floor Deck) – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Bekisting permanen sekaligus tulangan untuk pelat lantai beton komposit pada bangunan bertingkat.',
                'category'  => 'Baja Ringan',
                'icon'      => '⊓',
                'intro'     => 'Bondek atau floor deck adalah lembaran baja bergelombang yang berfungsi sekaligus sebagai bekisting permanen dan tulangan tarik pada sistem pelat lantai beton komposit. Material ini merevolusi cara konstruksi pelat lantai gedung bertingkat dengan menghilangkan kebutuhan bekisting kayu sementara. Karena itu, bondek sangat populer pada konstruksi gedung bertingkat yang mengejar kecepatan dan efisiensi. Selain itu, profilnya yang bergelombang meningkatkan kekuatan sambungan dengan beton.',
                'pengertian'=> 'Bondek adalah pelat baja bergelombang (profiled steel deck) yang diletakkan di atas balok baja atau beton sebagai dasar pengecoran pelat lantai. Permukaan bondek memiliki emboss atau indentasi khusus yang meningkatkan ikatan mekanis dengan beton. Dengan demikian, bondek dan beton bekerja secara komposit dalam menahan beban. Selain itu, profil bergelombangnya memberikan kekuatan pada arah lebar sehingga dapat menopang beban segar beton sebelum mengeras.',
                'fungsi'    => [
                    ['judul' => 'Bekisting permanen pelat lantai', 'isi' => 'Bondek menggantikan bekisting kayu sementara pada pelat lantai beton. Setelah beton mengeras, bondek tetap terpasang dan menjadi bagian dari pelat.'],
                    ['judul' => 'Tulangan tarik komposit', 'isi' => 'Bondek bekerja sebagai tulangan tarik pada sistem pelat komposit, mengurangi atau menghilangkan kebutuhan wiremesh di bagian bawah pelat.'],
                    ['judul' => 'Formwork untuk bangunan bertingkat', 'isi' => 'Pada bangunan bertingkat, bondek dipasang span antar balok sehingga pengecoran bisa dilakukan lantai per lantai dengan cepat tanpa menunggu bekisting bawah dibongkar.'],
                    ['judul' => 'Atap deck pada bangunan industri', 'isi' => 'Bondek dengan profil lebih dalam digunakan sebagai deck atap (roof deck) pada bangunan industri dan komersial yang memerlukan bentang lebih panjang.'],
                ],
                'jenis'     => [
                    ['nama' => 'Floor Deck Standar (55 mm)', 'deskripsi' => 'Profil dengan tinggi gelombang 55 mm untuk bentang antar balok 2,5–3,0 m. Paling umum digunakan pada gedung bertingkat.'],
                    ['nama' => 'Floor Deck Dalam (75 mm)', 'deskripsi' => 'Profil lebih dalam 75 mm untuk bentang lebih panjang hingga 4,5 m. Mengurangi jumlah balok yang diperlukan sehingga lebih ekonomis.'],
                    ['nama' => 'Roof Deck', 'deskripsi' => 'Profil khusus untuk atap yang memberikan kekakuan dan kemampuan menahan beban mati dan hidup tanpa perlu penyangga sementara.'],
                ],
                'keunggulan' => [
                    'Menghilangkan kebutuhan bekisting kayu sementara',
                    'Mempercepat jadwal konstruksi pelat lantai',
                    'Bekerja komposit dengan beton, mengurangi kebutuhan tulangan',
                    'Lapisan galvalum tahan korosi',
                    'Lebar efektif 600 mm per lembar, pemasangan cepat',
                    'Tersedia tebal 0,75 mm dan 1,0 mm',
                ],
                'ukuran_intro' => 'Bondek tersedia dalam beberapa tebal. Panjang disesuaikan dengan jarak antar balok (span) proyek.',
                'tabel_header' => ['Tebal (mm)', 'Lebar Efektif (mm)', 'Tinggi Profil (mm)', 'Max Span (m)', 'Coating'],
                'tabel_data'   => [
                    ['0,75', '600', '55', '3,0', 'Galvalum AZ150'],
                    ['1,00', '600', '55', '3,5', 'Galvalum AZ150'],
                    ['0,75', '600', '75', '3,5', 'Galvalum AZ150'],
                    ['1,00', '600', '75', '4,5', 'Galvalum AZ150'],
                ],
                'kesimpulan' => 'Bondek adalah inovasi konstruksi yang mengoptimalkan kecepatan, efisiensi material, dan kekuatan pelat lantai secara bersamaan. Dengan menggabungkan fungsi bekisting dan tulangan dalam satu material, bondek secara signifikan mengurangi biaya dan waktu konstruksi. Selain itu, sistem komposit yang dihasilkan memberikan pelat lantai yang kuat dan efisien untuk bangunan bertingkat modern.',
                'spesifikasi' => ['Material' => 'Galvalum AZ150', 'Tebal' => '0,75 – 1,0 mm', 'Lebar Efektif' => '600 mm', 'Profil' => '55 mm / 75 mm', 'Panjang' => 'Sesuai pesanan'],
            ],

            // ─── ANGKUR ──────────────────────────────────────────────────
            'angkur' => [
                'name'      => 'Angkur',
                'title'     => 'Angkur – Pengertian, Fungsi, Jenis, Ukuran Teknis Konstruksi',
                'subtitle'  => 'Komponen pengikat struktural untuk menahan gaya tarik dan geser pada sambungan beton dan baja.',
                'category'  => 'Aksesori',
                'icon'      => '⚓',
                'intro'     => 'Angkur merupakan komponen pengikat struktural yang berfungsi menahan gaya tarik serta gaya geser pada sambungan beton dan baja. Material ini bekerja sebagai penyatu antara elemen struktural agar sambungan tetap kaku dan stabil. Karena itu, angkur selalu masuk dalam perhitungan utama pada desain fondasi dan struktur baja. Selain itu, desainnya mengikuti standar teknis tertentu untuk memastikan kekuatan optimal.',
                'pengertian'=> 'Angkur adalah batang baja berulir atau berpola tertentu yang digunakan sebagai penahan struktur pada fondasi. Material ini menyalurkan beban dari elemen atas ke beton. Dengan demikian, kekuatannya sangat memengaruhi performa sambungan. Selain itu, angkur membantu menjaga posisi kolom, mesin, dan pelat dasar tetap presisi selama operasi bangunan.',
                'fungsi'    => [
                    ['judul' => 'Menahan gaya tarik dan geser', 'isi' => 'Gaya horizontal dan vertikal dapat memindahkan struktur. Oleh karena itu, angkur menjaga elemen tetap stabil meskipun beban berubah.'],
                    ['judul' => 'Mengikat kolom baja pada baseplate', 'isi' => 'Kolom baja memerlukan penguncian yang kuat agar tidak bergeser akibat angin atau gempa. Angkur memastikan posisi tetap terjaga.'],
                    ['judul' => 'Menahan getaran mesin industri', 'isi' => 'Pemasangan mesin berat memerlukan anchor bolt untuk mengurangi pergeseran akibat getaran yang dihasilkan selama operasional mesin.'],
                    ['judul' => 'Memperkuat sambungan beton–baja', 'isi' => 'Karena posisinya berada di area kritis, angkur mendukung kinerja sambungan beton-baja secara keseluruhan dan menjamin kekakuan sistem.'],
                ],
                'jenis'     => [
                    ['nama' => 'J-Bolt (Angkur J)', 'deskripsi' => 'Tipe ini memiliki bentuk cekungan seperti huruf J. Geometri tersebut meningkatkan daya tarik sehingga cocok untuk fondasi kolom dan pelat dasar.'],
                    ['nama' => 'L-Bolt (Angkur L)', 'deskripsi' => 'Memiliki sudut 90° pada bagian bawah. Karena strukturnya sederhana, tipe ini efektif untuk fondasi ringan hingga menengah.'],
                    ['nama' => 'U-Bolt', 'deskripsi' => 'Ujung ganda membuat angkur ini mampu menjepit pipa atau batang silinder. Selain itu, U-Bolt sering digunakan pada rangka mekanikal.'],
                    ['nama' => 'Chemical Anchor', 'deskripsi' => 'Tipe ini menggunakan resin kimia sebagai pengikat. Dengan sistem tersebut, angkur dapat menahan beban tinggi pada beton yang sudah mengeras.'],
                    ['nama' => 'Wedge Anchor / Drop-in Anchor', 'deskripsi' => 'Tipe ekspansi yang bermanfaat untuk instalasi cepat. Karena mekanismenya langsung mengunci, pemasangan menjadi lebih efisien.'],
                ],
                'keunggulan' => [
                    'Kekuatan tarik tinggi, baik untuk struktur baja maupun mesin industri',
                    'Ketahanan terhadap deformasi, terutama pada tipe galvanis',
                    'Instalasi fleksibel, dapat dilakukan sebelum atau setelah pengecoran',
                    'Presisi tinggi, mendukung keakuratan posisi kolom dan baseplate',
                    'Kompatibel dengan berbagai aplikasi, mulai dari bangunan ringan hingga industri berat',
                    'Tersedia berbagai tipe dan ukuran sesuai kebutuhan struktural',
                ],
                'ukuran_intro' => 'Angkur tersedia dalam berbagai jenis dan ukuran sesuai beban dan kedalaman pondasi.',
                'tabel_header' => ['Jenis', 'Diameter', 'Panjang', 'Material'],
                'tabel_data'   => [
                    ['J-Bolt',         'M8–M20',  '20–60 cm', 'Baja karbon / galvanis'],
                    ['L-Bolt',         'M10–M24', '25–70 cm', 'Baja mutu tinggi'],
                    ['U-Bolt',         'M6–M16',  '5–30 cm',  'Baja galvanis'],
                    ['Wedge Anchor',   'M8–M20',  '6–20 cm',  'Stainless / galvanis'],
                    ['Chemical Anchor','M8–M30',  'Variatif', 'Baja + resin kimia'],
                ],
                'kesimpulan' => 'Angkur memiliki peran penting dalam menjaga stabilitas sambungan struktur. Dengan memilih tipe dan ukuran yang tepat, kekuatan konstruksi dapat meningkat secara signifikan. Selain itu, penggunaan angkur yang sesuai standar akan memastikan keamanan bangunan dalam jangka panjang.',
                'spesifikasi' => ['Grade' => '4.8 / 8.8', 'Ukuran' => 'M6 – M48', 'Tipe' => 'J-bolt / L-bolt / U-bolt', 'Panjang' => '5 – 100 cm', 'Finish' => 'Galvanis / Hitam'],
            ],

            // ─── MUR DAN BAUT ────────────────────────────────────────────
            'mur-baut' => [
                'name'      => 'Mur dan Baut',
                'title'     => 'Mur dan Baut – Pengertian, Fungsi, Jenis, Ukuran Standar',
                'subtitle'  => 'Komponen pengikat baja struktural, mesin, dan konstruksi dalam berbagai grade kekuatan.',
                'category'  => 'Aksesori',
                'icon'      => '⚙',
                'intro'     => 'Mur dan baut adalah komponen pengikat mekanis yang paling fundamental dalam konstruksi baja dan pemasangan peralatan industri. Komponen ini memungkinkan sambungan yang dapat dibuka kembali (reversible) berbeda dengan pengelasan. Karena itu, mur dan baut menjadi pilihan utama untuk sambungan yang memerlukan pemeliharaan atau penggantian komponen di kemudian hari. Selain itu, tersedia dalam berbagai grade kekuatan untuk menyesuaikan tingkat pembebanan.',
                'pengertian'=> 'Mur adalah komponen berulir dalam (female thread) berbentuk segi enam yang berfungsi sebagai pengunci baut. Baut adalah batang berulir luar (male thread) dengan kepala yang berfungsi sebagai pengikat. Keduanya bekerja bersama dengan memanfaatkan prinsip ulir untuk menghasilkan gaya pengikatan (clamping force). Dengan demikian, sambungan baut-mur dapat menahan gaya tarik, geser, dan torsi sesuai grade yang dipilih.',
                'fungsi'    => [
                    ['judul' => 'Sambungan struktural baja (High-Strength Bolt)', 'isi' => 'Baut mutu tinggi grade 8.8 atau 10.9 digunakan untuk sambungan struktural pada konstruksi baja seperti sambungan balok-kolom, pelat sambung, dan gusset plate.'],
                    ['judul' => 'Pemasangan dan pondasi mesin', 'isi' => 'Baut pondasi dan anchor bolt digunakan untuk mengikat mesin ke lantai beton, memastikan posisi yang tetap dan menahan getaran selama operasional.'],
                    ['judul' => 'Sambungan rangka baja ringan', 'isi' => 'Baut self-drilling dan self-tapping digunakan untuk sambungan rangka baja ringan, atap galvalum, dan panel cladding tanpa pre-drilling.'],
                    ['judul' => 'Pemasangan komponen mekanikal dan elektrikal', 'isi' => 'Berbagai jenis baut digunakan untuk pemasangan pipa, kabel tray, peralatan HVAC, dan komponen mekanikal-elektrikal pada bangunan.'],
                ],
                'jenis'     => [
                    ['nama' => 'Baut Hex (Hexagon Bolt)', 'deskripsi' => 'Baut dengan kepala segi enam, paling umum digunakan untuk sambungan struktural. Tersedia grade 4.8, 8.8, dan 10.9.'],
                    ['nama' => 'Baut Carriage (Baut Kereta)', 'deskripsi' => 'Kepala setengah bulat dengan leher persegi di bawah kepala. Digunakan pada sambungan kayu dan konstruksi ringan.'],
                    ['nama' => 'Baut High Tension (HT Bolt)', 'deskripsi' => 'Baut mutu tinggi grade 8.8–10.9 khusus untuk sambungan struktural baja yang memerlukan gaya pengikatan sangat besar dan presisi.'],
                    ['nama' => 'Self-Drilling Screw (Sekrup Roofing)', 'deskripsi' => 'Sekrup dengan ujung bor yang dapat menembus baja ringan tanpa pre-drilling. Digunakan untuk pemasangan atap galvalum dan panel cladding.'],
                ],
                'keunggulan' => [
                    'Tersedia grade 4.8, 8.8, dan 10.9 sesuai kebutuhan kekuatan',
                    'Sambungan dapat dibongkar untuk pemeliharaan',
                    'Ukuran M6 hingga M36 tersedia lengkap',
                    'Tersedia dalam finish galvanis dan hitam',
                    'Diproduksi sesuai standar ISO, DIN, dan SNI',
                    'Berbagai tipe kepala untuk kemudahan pemasangan',
                ],
                'ukuran_intro' => 'Mur dan baut tersedia dalam berbagai diameter metrik (M) dan grade kekuatan. Panjang baut bervariasi dari 20 mm hingga 300 mm.',
                'tabel_header' => ['Diameter', 'Grade', 'Kekuatan Tarik (MPa)', 'Tegangan Leleh (MPa)', 'Finish'],
                'tabel_data'   => [
                    ['M6 – M36',  '4.8',  '400', '320', 'Hitam / Galvanis'],
                    ['M6 – M36',  '8.8',  '800', '640', 'Hitam / Galvanis'],
                    ['M6 – M36',  '10.9', '1000','900', 'Hitam / Galvanis'],
                    ['M8 – M24',  'A2-70','700', '450', 'Stainless SS304'],
                    ['M8 – M24',  'A4-80','800', '600', 'Stainless SS316'],
                ],
                'kesimpulan' => 'Mur dan baut adalah komponen pengikat yang tidak tergantikan dalam konstruksi baja dan industri. Dengan memilih grade yang tepat sesuai perhitungan sambungan, kekuatan dan keandalan struktur dapat terjamin. Selain itu, kemampuan sambungan untuk dibuka kembali memberikan fleksibilitas dalam perawatan dan modifikasi bangunan.',
                'spesifikasi' => ['Grade' => '4.8 / 8.8 / 10.9', 'Ukuran' => 'M6 – M36', 'Standar' => 'ISO / DIN / SNI', 'Panjang' => '20 – 300 mm', 'Finish' => 'Hitam / Galvanis'],
            ],

            // ─── KAWAT ───────────────────────────────────────────────────
            'kawat' => [
                'name'      => 'Kawat Duri & Harmonika',
                'title'     => 'Kawat Duri & Harmonika – Pengertian, Fungsi, Ukuran Standar',
                'subtitle'  => 'Kawat pengaman perimeter untuk pagar keamanan, pembatas area industri, dan pertahanan properti.',
                'category'  => 'Kawat',
                'icon'      => '≋',
                'intro'     => 'Kawat duri dan kawat harmonika adalah material pengaman perimeter yang efektif dan ekonomis untuk berbagai kebutuhan pembatasan dan pengamanan area. Kedua produk ini melengkapi sistem pagar untuk meningkatkan faktor keamanan secara signifikan. Karena itu, kawat duri dan harmonika banyak digunakan di area industri, perkebunan, peternakan, dan fasilitas keamanan. Selain itu, tersedia juga kawat loket untuk kebutuhan kandang dan saringan.',
                'pengertian'=> 'Kawat duri adalah kawat baja berlapis zinc dengan duri-duri tajam yang dipasang secara berkala sepanjang kawat. Kawat harmonika adalah anyaman kawat berbentuk belah ketupat (rhombus) yang fleksibel. Kawat loket adalah anyaman kawat segi empat untuk kandang dan saringan. Dengan demikian, ketiganya melayani kebutuhan keamanan dan pembatas yang berbeda sesuai tingkat keamanan yang diperlukan.',
                'fungsi'    => [
                    ['judul' => 'Pengamanan perimeter properti dan lahan', 'isi' => 'Kawat duri dipasang di atas pagar untuk mencegah pelintasan dari luar. Sangat efektif untuk properti industri, perkebunan, dan fasilitas keamanan.'],
                    ['judul' => 'Pagar perkebunan dan pertanian', 'isi' => 'Kawat harmonika dan kawat duri digunakan untuk pagar perkebunan dan pertanian yang membatasi hewan ternak dan mencegah pencurian tanaman.'],
                    ['judul' => 'Kandang hewan dan penangkaran', 'isi' => 'Kawat loket dengan berbagai ukuran mesh digunakan sebagai kandang ayam, kelinci, ikan, dan berbagai hewan lainnya serta jaring pengaman.'],
                    ['judul' => 'Saringan dan filter industri', 'isi' => 'Kawat loket mesh halus digunakan sebagai saringan material, filter industri, dan pengaman lubang ventilasi pada bangunan dan peralatan.'],
                ],
                'jenis'     => [
                    ['nama' => 'Kawat Duri (Barbed Wire)', 'deskripsi' => 'Kawat baja berlapis galvanis dengan duri berpasangan setiap 10–15 cm. Tersedia dalam 2 strand (helai) dengan berbagai jarak antar duri.'],
                    ['nama' => 'Kawat Harmonika (Chain Link)', 'deskripsi' => 'Anyaman kawat galvanis berbentuk belah ketupat yang fleksibel dan mudah dipasang. Sering digunakan untuk pagar perimeter dan lapangan olahraga.'],
                    ['nama' => 'Kawat Loket (Welded Mesh)', 'deskripsi' => 'Anyaman kawat las segi empat dengan berbagai ukuran mesh. Cocok untuk kandang, saringan, dan pengaman lubang dengan ketebalan yang bervariasi.'],
                ],
                'keunggulan' => [
                    'Lapisan galvanis tahan korosi untuk pemasangan outdoor',
                    'Efektif mencegah pelintasan perimeter',
                    'Harga ekonomis dengan pemasangan yang mudah',
                    'Tersedia roll 10m, 25m, dan 50m',
                    'Berbagai ukuran mesh dan diameter kawat',
                    'Dapat dikombinasikan dengan pagar BRC dan dinding',
                ],
                'ukuran_intro' => 'Kawat duri, harmonika, dan loket tersedia dalam berbagai spesifikasi diameter dan ukuran mesh.',
                'tabel_header' => ['Tipe', 'Dia. Kawat (mm)', 'Ukuran / Mesh', 'Panjang Roll', 'Material'],
                'tabel_data'   => [
                    ['Kawat Duri',     '2,0 – 2,8', 'Jarak duri 10–15 cm', '25m / 50m', 'Galvanis / Hitam'],
                    ['Kawat Harmonika', '2,0 – 3,0', '50×50 / 60×60 mm',   '10m / 25m', 'Galvanis / PVC'],
                    ['Kawat Harmonika', '2,0 – 3,0', '75×75 / 100×100 mm', '10m / 25m', 'Galvanis / PVC'],
                    ['Kawat Loket',    '1,2 – 2,0', '12×12 / 25×25 mm',   '1m × 30m',  'Galvanis'],
                    ['Kawat Loket',    '1,6 – 2,5', '50×50 / 100×100 mm', '1m × 20m',  'Galvanis'],
                ],
                'kesimpulan' => 'Kawat duri, harmonika, dan loket adalah solusi keamanan perimeter yang ekonomis dan efektif untuk berbagai kebutuhan. Dengan memilih jenis dan ukuran yang sesuai fungsi dan tingkat keamanan, sistem pembatas dapat bekerja optimal. Selain itu, lapisan galvanis memastikan ketahanan jangka panjang di berbagai kondisi cuaca.',
                'spesifikasi' => ['Tipe' => 'Duri / Harmonika / Loket', 'Material' => 'Baja galvanis / hitam', 'Panjang Roll' => '10m – 50m', 'Lebar' => 'Berbagai ukuran', 'Finish' => 'Galvanis / PVC'],
            ],

        ]; // end allProducts
    }

    public function show(string $slug)
    {
        $product = Product::where('slug', $slug)
                        ->where('is_active', true)
                        ->firstOrFail();

        return view('products.show', ['product' => $product]);
    }

    public function index()
    {
        // Ambil semua produk aktif dari database
        $products = Product::where('is_active', true)
                        ->orderBy('category')
                        ->get();

        return view('products', compact('products'));
    }
}